[package]
name = "keyloom"
version = "0.1.0"
edition = "2024"

[dependencies]
evdev = "0.13"
tokio = { version = "1", features = ["time"] }

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = [
    "a11y",
    "dbus-config",
    "multi-window",
    "tokio",
    "wayland",
    "wgpu",
    "winit",
]
