[package]
name = "keyloom"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[dependencies]
evdev = "0.13"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["process", "time"] }

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = [
    "a11y",
    "dbus-config",
    "multi-window",
    "process",
    "tokio",
    "wayland",
    "wgpu",
    "winit",
]
