//! Management of the xremap systemd *user* service.
//!
//! Keyloom asks systemd's user manager about the unit, and tells it
//! what to do, over D-Bus ([`crate::systemd`]). The header follows the
//! unit live ([`watch`]): its state when Keyloom opens, then every
//! change systemd announces, so a crash, or a stop made outside
//! Keyloom, shows up as it happens. Applying a configuration means
//! restarting the unit so xremap re-reads the generated file. The
//! header's status chip stops and starts the unit, which is how a
//! keyboard the remapper holds exclusively is released. First-run
//! setup ([`crate::setup`]) installs the unit itself: a file in the
//! user's systemd configuration that runs the installed xremap with
//! Keyloom's generated configuration, told which desktop to ask for
//! application-specific rules when the binary understands that.
//! systemd has no request that saves a unit from its text, so writing
//! that file, and backing up one the user wrote, is file work here.

use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::sync::{Mutex, PoisonError};

use cosmic::iced::futures::channel::mpsc;
use cosmic::iced::futures::{FutureExt, SinkExt, Stream, StreamExt};
use tokio::sync::OnceCell;
use zbus::message::Sequence;

use crate::session::Desktop;
use crate::systemd::{self, Change, Manager};
use crate::xremap;

pub use crate::systemd::Error;

/// The systemd user unit Keyloom manages.
pub const UNIT: &str = "xremap.service";

/// First line of the unit file Keyloom installs. A unit without it
/// belongs to the user and is backed up before being replaced, never
/// silently overwritten.
pub const UNIT_MARKER: &str =
    "# Generated by Keyloom. Do not edit by hand; Keyloom overwrites this file.";

/// Whether remapping should be running: the status chip's two
/// positions, and what a switch still in flight is heading for.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Remapping {
    On,
    Off,
}

/// State of the xremap user service, as far as systemd knows.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Status {
    /// The unit is running.
    Active,
    /// The unit is on its way up, and xremap has not been started yet:
    /// on Wayland, the unit waits for the compositor first.
    Starting,
    /// The unit is on its way down.
    Stopping,
    /// xremap exited without being asked to, and systemd is about to
    /// start it again.
    Restarting,
    /// The unit exists but is not running.
    Inactive,
    /// The unit exists and its last run failed.
    Failed,
    /// No `xremap.service` user unit is registered.
    NotFound,
    /// systemd's user manager cannot be reached (not a systemd session).
    Unavailable,
}

impl Status {
    /// The state a unit's `LoadState`, `ActiveState`, and `SubState`
    /// describe. A state newer than the ones known here reads as
    /// stopped, the way `systemctl is-active` counts anything but
    /// `active` as not running.
    pub fn of(load_state: &str, active_state: &str, sub_state: &str) -> Self {
        if load_state == "not-found" {
            return Self::NotFound;
        }
        match (active_state, sub_state) {
            // On its way to an automatic restart, a service passes
            // through a stopped or failed state that does not last.
            (
                _,
                "auto-restart"
                | "auto-restart-queued"
                | "dead-before-auto-restart"
                | "failed-before-auto-restart",
            ) => Self::Restarting,
            // xremap has no reload of its own; a running unit busy with
            // one still runs.
            ("active" | "reloading" | "refreshing", _) => Self::Active,
            ("activating", _) => Self::Starting,
            ("deactivating", _) => Self::Stopping,
            ("failed", _) => Self::Failed,
            _ => Self::Inactive,
        }
    }

    /// User-facing state label. xremap and systemd are implementation
    /// details, so the wording stays generic.
    pub fn label(self) -> &'static str {
        match self {
            Self::Active => "Remapping Enabled",
            Self::Starting => "Starting Remapping",
            Self::Stopping => "Stopping Remapping",
            Self::Restarting => "Restarting Remapping",
            // A stopped unit is a paused one, however it came to be
            // stopped: the distinction is Keyloom's, not the user's.
            Self::Inactive => "Remapping Paused",
            Self::Failed => "Remapping Failed",
            Self::NotFound => "Remapping not set up",
            Self::Unavailable => "Remapping Unavailable",
        }
    }
}

/// What systemd reports about the unit.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Unit {
    /// Whether it runs, or exists at all.
    pub status: Status,
    /// Whether the unit starts with the graphical session.
    pub enabled: bool,
    /// The unit file systemd loaded, when it found one.
    pub fragment_path: Option<PathBuf>,
}

impl Unit {
    const UNAVAILABLE: Self = Self {
        status: Status::Unavailable,
        enabled: false,
        fragment_path: None,
    };

    /// Read systemd's report on the unit.
    fn from_state(state: &systemd::UnitState) -> Self {
        let status = Status::of(&state.load_state, &state.active_state, &state.sub_state);
        if status == Status::NotFound {
            return Self {
                status,
                enabled: false,
                fragment_path: None,
            };
        }
        Self {
            status,
            enabled: matches!(
                state.unit_file_state.as_str(),
                "enabled" | "enabled-runtime"
            ),
            fragment_path: Some(state.fragment_path.as_str())
                .filter(|path| !path.is_empty())
                .map(PathBuf::from),
        }
    }
}

/// The unit's state at one moment, numbered so that reports can be put
/// in order: whichever way two reports travel, the higher revision
/// describes the later moment. The revision only moves on when the
/// state changes.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Snapshot {
    pub status: Status,
    pub revision: u64,
}

#[cfg(test)]
impl Snapshot {
    /// A report of `status` newer than every one made before it, as the
    /// running service would deliver it; for staging states in tests.
    pub fn latest(status: Status) -> Self {
        use std::sync::atomic::{AtomicU64, Ordering};
        static REVISION: AtomicU64 = AtomicU64::new(0);
        Self {
            status,
            revision: REVISION.fetch_add(1, Ordering::Relaxed) + 1,
        }
    }
}

/// The newest state any request brought back, and where on the shared
/// connection its reply was received (`P`, a receive position). Replies
/// are received in the order systemd sent them, so a reply received
/// earlier describes an earlier moment, even when it is handled later.
struct Latest<P> {
    position: Option<P>,
    snapshot: Option<Snapshot>,
}

impl<P: Ord> Latest<P> {
    const fn new() -> Self {
        Self {
            position: None,
            snapshot: None,
        }
    }

    /// Take in `status` from a reply received at `position` (`None`
    /// for a request that never reached systemd, which is news whenever
    /// it comes), unless a reply received after it is in already.
    /// Returns the newest snapshot either way.
    fn record(&mut self, position: Option<P>, status: Status) -> Snapshot {
        if let (Some(position), Some(latest), Some(snapshot)) =
            (&position, &self.position, self.snapshot)
            && position <= latest
        {
            return snapshot;
        }
        if position.is_some() {
            self.position = position;
        }
        let snapshot = match self.snapshot {
            Some(snapshot) if snapshot.status == status => snapshot,
            previous => Snapshot {
                status,
                revision: previous.map_or(1, |previous| previous.revision + 1),
            },
        };
        self.snapshot = Some(snapshot);
        snapshot
    }
}

/// Every report on the unit's state goes through here.
static LATEST: Mutex<Latest<Sequence>> = Mutex::new(Latest::new());

fn record(position: Option<Sequence>, status: Status) -> Snapshot {
    LATEST
        .lock()
        .unwrap_or_else(PoisonError::into_inner)
        .record(position, status)
}

/// The connection to systemd every request shares, made on first use.
/// Sharing it is what puts the replies to different requests in one
/// order ([`Latest`]).
async fn manager() -> Result<&'static Manager, Error> {
    static MANAGER: OnceCell<Manager> = OnceCell::const_new();
    MANAGER.get_or_try_init(Manager::session).await
}

/// Ask for the unit's state, and report it or whatever newer state
/// another request has brought back meanwhile.
async fn observe(manager: &Manager) -> Snapshot {
    match manager.unit(UNIT).await {
        Ok((state, position)) => record(Some(position), Unit::from_state(&state).status),
        Err(_) => record(None, Status::Unavailable),
    }
}

/// What systemd reports about the unit now, for setup's checks.
pub async fn inspect() -> Unit {
    let Ok(manager) = manager().await else {
        return Unit::UNAVAILABLE;
    };
    match manager.unit(UNIT).await {
        Ok((state, _)) => Unit::from_state(&state),
        Err(_) => Unit::UNAVAILABLE,
    }
}

/// Follow the unit: its state now, then its state after every change
/// systemd announces, whoever made it, for as long as the session bus
/// is there. States are only reported once each.
pub fn watch() -> impl Stream<Item = Snapshot> + Send {
    cosmic::iced::stream::channel(1, follow)
}

async fn follow(mut output: mpsc::Sender<Snapshot>) {
    let manager = match manager().await {
        Ok(manager) => manager,
        Err(err) => {
            eprintln!("keyloom: cannot follow the remapping service: {err}");
            let _ = output.send(record(None, Status::Unavailable)).await;
            return;
        }
    };
    // Listen before the first look, so a change between the two is
    // not missed.
    let mut changes = match manager.changes(UNIT).await {
        Ok(changes) => changes,
        Err(err) => {
            // Keyloom's own switches and applies still report what they
            // leave the unit in.
            eprintln!("keyloom: remapping changes made elsewhere will not show: {err}");
            let _ = output.send(observe(manager).await).await;
            return;
        }
    };
    subscribe(manager).await;
    let mut reported = 0;
    loop {
        let snapshot = observe(manager).await;
        if snapshot.revision > reported {
            reported = snapshot.revision;
            if output.send(snapshot).await.is_err() {
                return;
            }
        }
        // One look covers every change already announced, so a burst
        // of them costs one.
        let mut next = changes.next().await;
        loop {
            match next {
                // A manager that left cannot be subscribed to; the one
                // that takes its place announces itself the same way.
                Some(Change::Manager) => {
                    let _ = manager.subscribe().await;
                }
                Some(Change::Unit) => {}
                // The connection closed: systemd can no longer be asked.
                None => {
                    let _ = output.send(record(None, Status::Unavailable)).await;
                    return;
                }
            }
            match changes.next().now_or_never() {
                Some(change) => next = change,
                None => break,
            }
        }
    }
}

/// Have systemd announce the unit's changes, which it does only for
/// subscribers. Without it, the header still learns what Keyloom's own
/// requests leave the unit in.
async fn subscribe(manager: &Manager) {
    if let Err(err) = manager.subscribe().await {
        eprintln!("keyloom: remapping changes made elsewhere will not show: {err}");
    }
}

/// Where Keyloom installs its unit:
/// `$XDG_CONFIG_HOME/systemd/user/xremap.service` (usually `~/.config`),
/// which systemd reads ahead of anything a package installed.
pub fn unit_path() -> Option<PathBuf> {
    Some(
        xremap::config_home()?
            .join("systemd")
            .join("user")
            .join(UNIT),
    )
}

/// Waits for the compositor's Wayland socket before xremap starts,
/// up to 30 seconds. The graphical session target can be reached
/// before the socket exists, and xremap connects to the compositor
/// for application-specific rules.
const WAIT_FOR_WAYLAND: &str = "/bin/sh -c 'for i in $(seq 1 30); do \
                                ls $XDG_RUNTIME_DIR/wayland-* >/dev/null 2>&1 && exit 0; \
                                sleep 1; done; exit 1'";

/// How the unit starts xremap, beyond the binary and the configuration.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Launch {
    /// The desktop xremap should ask which window is in front, passed
    /// as `--desktop`. `None` leaves the choice to xremap, which is
    /// also all that a binary older than 0.15.13 understands.
    pub desktop: Option<Desktop>,
    /// Wait for the compositor's Wayland socket before starting. On an
    /// X11 session the socket never appears, so the wait would only
    /// keep the unit from ever starting.
    pub wait_for_wayland: bool,
}

impl Default for Launch {
    /// A Wayland session with the desktop left to xremap: the unit as
    /// Keyloom always installed it.
    fn default() -> Self {
        Self {
            desktop: None,
            wait_for_wayland: true,
        }
    }
}

/// The unit file Keyloom installs, modeled on a hand-written unit that
/// has run xremap on COSMIC for a long time: run the given xremap
/// binary with Keyloom's generated configuration, follow keyboards as
/// they are plugged in, live with the graphical session, wait for the
/// compositor before starting (on Wayland), and keep xremap running.
///
/// Logging stays at `info`: xremap's `debug` level writes every key
/// press to the journal.
pub fn unit_file(binary: &Path, config: &Path, launch: Launch) -> String {
    let wait = if launch.wait_for_wayland {
        format!("ExecStartPre={WAIT_FOR_WAYLAND}\n")
    } else {
        String::new()
    };
    let desktop = launch.desktop.map_or_else(String::new, |desktop| {
        format!("  --desktop {} \\\n", desktop.flag())
    });
    format!(
        "{UNIT_MARKER}\n\
         [Unit]\n\
         Description=Keyboard remapping for Keyloom (xremap)\n\
         Documentation={}\n\
         After=graphical-session.target input-method.target\n\
         PartOf=graphical-session.target\n\
         \n\
         [Service]\n\
         Restart=always\n\
         RestartSec=5\n\
         {wait}\
         Environment=RUST_LOG=info\n\
         ExecStart={} \\\n\
         {desktop}\
         \x20 --watch \\\n\
         \x20 {}\n\
         \n\
         [Install]\n\
         WantedBy=graphical-session.target\n",
        env!("CARGO_PKG_REPOSITORY"),
        quote(binary),
        quote(config)
    )
}

/// Quote a path for a unit's command line the way systemd expects:
/// double quotes with backslash escapes, and only when needed.
fn quote(path: &Path) -> String {
    let path = path.to_string_lossy();
    if !path.is_empty()
        && !path
            .chars()
            .any(|c| c.is_whitespace() || matches!(c, '"' | '\'' | '\\' | ';'))
    {
        return path.into_owned();
    }
    let mut quoted = String::with_capacity(path.len() + 2);
    quoted.push('"');
    for c in path.chars() {
        if matches!(c, '"' | '\\') {
            quoted.push('\\');
        }
        quoted.push(c);
    }
    quoted.push('"');
    quoted
}

/// Result of installing the unit file.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum InstallOutcome {
    /// File created or replaced; systemd has to reload to see it.
    Written,
    /// File already had exactly this content.
    Unchanged,
}

/// Write the unit file to [`unit_path`]. A file there that Keyloom did
/// not write is backed up beside it first.
///
/// # Errors
///
/// When there is no home directory or the file cannot be written.
pub fn install(text: &str) -> io::Result<InstallOutcome> {
    let path = unit_path().ok_or_else(|| {
        io::Error::new(io::ErrorKind::NotFound, "no home directory to write into")
    })?;
    install_to(&path, text)
}

/// [`install`] with an explicit target path.
///
/// # Errors
///
/// When an existing foreign file cannot be backed up, or the directory
/// or file cannot be written.
pub fn install_to(path: &Path, text: &str) -> io::Result<InstallOutcome> {
    if let Ok(existing) = fs::read_to_string(path) {
        if existing == text {
            return Ok(InstallOutcome::Unchanged);
        }
        if !existing.starts_with(UNIT_MARKER) {
            xremap::backup(path)?;
        }
    }
    let dir = path
        .parent()
        .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidInput, "unit path has no parent"))?;
    fs::create_dir_all(dir)?;
    let tmp = path.with_extension("service.tmp");
    fs::write(&tmp, text)?;
    fs::rename(&tmp, path)?;
    Ok(InstallOutcome::Written)
}

/// Make systemd read unit files again, after installing one.
///
/// # Errors
///
/// When systemd cannot be reached, or refuses.
pub async fn daemon_reload() -> Result<(), Error> {
    manager().await?.reload().await
}

/// Start the unit with every graphical session from now on.
///
/// # Errors
///
/// When systemd cannot be reached, or refuses (no unit file to enable).
pub async fn enable() -> Result<(), Error> {
    manager().await?.enable(UNIT).await
}

/// Restart the unit so xremap picks up the generated configuration.
/// Reports the state the restart left the unit in.
///
/// # Errors
///
/// Fails when systemd cannot be reached, or refuses the restart (a
/// missing unit, a start rate limit, a failing `ExecStartPre`).
pub async fn restart() -> Result<Snapshot, Error> {
    let manager = manager().await?;
    manager.restart(UNIT).await?;
    Ok(observe(manager).await)
}

/// Put remapping in the requested state: stopping the unit releases the
/// keyboards xremap grabbed, so they can be observed directly. Only the
/// status chip asks for this. Reports the state the switch left the
/// unit in, which is not always the one asked for: xremap can fail
/// right after starting, and a stop can end in failure.
///
/// # Errors
///
/// As [`restart`]. Starting an already-running unit, or stopping an
/// already-stopped one, succeeds without doing anything.
pub async fn set(remapping: Remapping) -> Result<Snapshot, Error> {
    let manager = manager().await?;
    match remapping {
        Remapping::On => manager.start(UNIT).await?,
        Remapping::Off => manager.stop(UNIT).await?,
    }
    Ok(observe(manager).await)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testing::TempDir;

    #[test]
    fn systemds_states_read_as_the_status_the_header_shows() {
        for (load, active, sub, expected) in [
            ("not-found", "inactive", "dead", Status::NotFound),
            ("loaded", "active", "running", Status::Active),
            ("loaded", "reloading", "reload", Status::Active),
            ("loaded", "refreshing", "running", Status::Active),
            ("loaded", "activating", "start-pre", Status::Starting),
            ("loaded", "activating", "start", Status::Starting),
            ("loaded", "deactivating", "stop-sigterm", Status::Stopping),
            ("loaded", "activating", "auto-restart", Status::Restarting),
            (
                "loaded",
                "activating",
                "auto-restart-queued",
                Status::Restarting,
            ),
            (
                "loaded",
                "failed",
                "failed-before-auto-restart",
                Status::Restarting,
            ),
            (
                "loaded",
                "inactive",
                "dead-before-auto-restart",
                Status::Restarting,
            ),
            ("loaded", "inactive", "dead", Status::Inactive),
            ("loaded", "failed", "failed", Status::Failed),
            ("masked", "inactive", "dead", Status::Inactive),
            ("loaded", "maintenance", "cleaning", Status::Inactive),
            ("", "", "", Status::Inactive),
        ] {
            assert_eq!(
                Status::of(load, active, sub),
                expected,
                "{load} {active} ({sub})"
            );
        }
    }

    fn state(load: &str, active: &str, unit_file: &str, fragment: &str) -> systemd::UnitState {
        systemd::UnitState {
            load_state: load.to_owned(),
            active_state: active.to_owned(),
            sub_state: String::new(),
            unit_file_state: unit_file.to_owned(),
            fragment_path: fragment.to_owned(),
        }
    }

    #[test]
    fn systemds_report_is_read_into_a_unit() {
        assert_eq!(
            Unit::from_state(&state("not-found", "inactive", "", "")),
            Unit {
                status: Status::NotFound,
                enabled: false,
                fragment_path: None,
            }
        );
        assert_eq!(
            Unit::from_state(&state(
                "loaded",
                "active",
                "enabled",
                "/home/me/.config/systemd/user/xremap.service"
            )),
            Unit {
                status: Status::Active,
                enabled: true,
                fragment_path: Some(PathBuf::from(
                    "/home/me/.config/systemd/user/xremap.service"
                )),
            }
        );
        let failed = Unit::from_state(&state("loaded", "failed", "disabled", ""));
        assert_eq!(failed.status, Status::Failed);
        assert!(!failed.enabled);
        assert_eq!(failed.fragment_path, None);
        assert!(Unit::from_state(&state("loaded", "inactive", "enabled-runtime", "")).enabled);
        assert!(!Unit::from_state(&state("loaded", "inactive", "linked", "")).enabled);
    }

    #[test]
    fn a_report_received_earlier_never_replaces_a_later_one() {
        let mut latest = Latest::<u32>::new();
        let running = latest.record(Some(10), Status::Active);
        assert_eq!(
            running,
            Snapshot {
                status: Status::Active,
                revision: 1,
            }
        );
        assert_eq!(
            latest.record(Some(11), Status::Active),
            running,
            "the same state again is nothing new"
        );

        let paused = latest.record(Some(20), Status::Inactive);
        assert_eq!(
            paused,
            Snapshot {
                status: Status::Inactive,
                revision: 2,
            }
        );
        // A reply received before that one but handled after it
        // describes an earlier moment.
        assert_eq!(latest.record(Some(15), Status::Stopping), paused);
        assert_eq!(latest.record(Some(20), Status::Active), paused);

        // A request that never reached systemd is news whenever it
        // comes, and replies are still ordered after it.
        let gone = latest.record(None, Status::Unavailable);
        assert_eq!(
            gone,
            Snapshot {
                status: Status::Unavailable,
                revision: 3,
            }
        );
        assert_eq!(latest.record(Some(18), Status::Active), gone);
        assert_eq!(
            latest.record(Some(30), Status::Active),
            Snapshot {
                status: Status::Active,
                revision: 4,
            }
        );
    }

    #[test]
    fn the_unit_runs_xremap_on_the_generated_config() {
        let unit = unit_file(
            Path::new("/usr/bin/xremap"),
            Path::new("/home/me/.config/xremap/keyloom.yml"),
            Launch::default(),
        );
        assert!(unit.starts_with(&format!("{UNIT_MARKER}\n[Unit]\n")));
        assert!(unit.contains(
            "\nExecStart=/usr/bin/xremap \\\n  --watch \\\n  /home/me/.config/xremap/keyloom.yml\n"
        ));
        assert_eq!(
            crate::setup::exec_start_of(&unit),
            "/usr/bin/xremap --watch /home/me/.config/xremap/keyloom.yml",
            "continuation lines join back into one command"
        );
        assert!(unit.contains("\nRestartSec=5\nExecStartPre=/bin/sh -c 'for i in $(seq 1 30); do ls $XDG_RUNTIME_DIR/wayland-* >/dev/null 2>&1 && exit 0; sleep 1; done; exit 1'\nEnvironment=RUST_LOG=info\n"));
        assert!(unit.contains("\nRestart=always\n"));
        assert!(unit.contains("\nWantedBy=graphical-session.target\n"));
        assert!(unit.contains("\nPartOf=graphical-session.target\n"));
        assert!(unit.contains("\nAfter=graphical-session.target input-method.target\n"));
        assert!(
            !unit.contains("--desktop"),
            "the desktop is left to xremap by default"
        );
        assert_eq!(
            unit,
            unit_file(
                Path::new("/usr/bin/xremap"),
                Path::new("/home/me/.config/xremap/keyloom.yml"),
                Launch::default(),
            ),
            "generation is deterministic"
        );
    }

    #[test]
    fn the_unit_names_the_desktop_when_asked_to() {
        let unit = unit_file(
            Path::new("/home/me/.local/bin/xremap"),
            Path::new("/home/me/.config/xremap/keyloom.yml"),
            Launch {
                desktop: Some(Desktop::Cosmic),
                wait_for_wayland: true,
            },
        );
        assert!(unit.contains(
            "\nExecStart=/home/me/.local/bin/xremap \\\n  --desktop cosmic \\\n  --watch \\\n  /home/me/.config/xremap/keyloom.yml\n"
        ));
        assert_eq!(
            crate::setup::exec_start_of(&unit),
            "/home/me/.local/bin/xremap --desktop cosmic --watch /home/me/.config/xremap/keyloom.yml",
            "the flag comes before the config, which xremap takes positionally"
        );
        assert!(unit.contains("\nExecStartPre="));
    }

    #[test]
    fn x11_sessions_do_not_wait_for_a_wayland_socket() {
        let unit = unit_file(
            Path::new("/usr/bin/xremap"),
            Path::new("/home/me/.config/xremap/keyloom.yml"),
            Launch {
                desktop: Some(Desktop::X11),
                wait_for_wayland: false,
            },
        );
        assert!(
            !unit.contains("ExecStartPre="),
            "nothing to wait for on X11"
        );
        assert!(unit.contains("\nRestartSec=5\nEnvironment=RUST_LOG=info\nExecStart=/usr/bin/xremap \\\n  --desktop x11 \\\n"));
        assert!(unit.starts_with(UNIT_MARKER));
    }

    #[test]
    fn paths_with_awkward_characters_are_quoted() {
        assert_eq!(quote(Path::new("/usr/bin/xremap")), "/usr/bin/xremap");
        assert_eq!(
            quote(Path::new("/home/my user/keyloom.yml")),
            "\"/home/my user/keyloom.yml\""
        );
        assert_eq!(
            quote(Path::new("/home/a\"b/c\\d.yml")),
            "\"/home/a\\\"b/c\\\\d.yml\""
        );
        assert_eq!(quote(Path::new("")), "\"\"");
    }

    #[test]
    fn installing_backs_up_foreign_units_but_not_our_own() {
        let dir = TempDir::new("service-install");
        let path = dir.path().join("systemd").join("user").join(UNIT);
        let ours = unit_file(
            Path::new("/usr/bin/xremap"),
            Path::new("/home/me/keyloom.yml"),
            Launch::default(),
        );

        assert_eq!(install_to(&path, &ours).unwrap(), InstallOutcome::Written);
        assert_eq!(fs::read_to_string(&path).unwrap(), ours);
        assert_eq!(install_to(&path, &ours).unwrap(), InstallOutcome::Unchanged);

        // Our own unit is rewritten in place.
        let updated = unit_file(
            Path::new("/usr/local/bin/xremap"),
            Path::new("/home/me/keyloom.yml"),
            Launch::default(),
        );
        assert_eq!(
            install_to(&path, &updated).unwrap(),
            InstallOutcome::Written
        );
        assert!(!path.with_file_name(format!("{UNIT}.bak")).exists());

        // Someone else's unit is kept beside the replacement.
        let theirs = "[Service]\nExecStart=/usr/bin/xremap /home/me/mine.yml\n";
        fs::write(&path, theirs).unwrap();
        assert_eq!(install_to(&path, &ours).unwrap(), InstallOutcome::Written);
        assert_eq!(fs::read_to_string(&path).unwrap(), ours);
        assert_eq!(
            fs::read_to_string(path.with_file_name(format!("{UNIT}.bak"))).unwrap(),
            theirs
        );
        assert!(!path.with_extension("service.tmp").exists());
    }

    #[test]
    fn the_unit_lives_in_the_user_configuration() {
        let path = unit_path().expect("a home directory");
        assert!(path.ends_with(Path::new("systemd/user").join(UNIT)));
        assert!(path.is_absolute());
    }
}
