//! Management of the xremap systemd *user* service.
//!
//! Status comes from `systemctl --user show` and applying a
//! configuration means restarting the unit so xremap re-reads the
//! generated file. The header's status chip stops and starts the unit,
//! which is how a keyboard the remapper holds exclusively is released.
//! First-run setup ([`crate::setup`]) installs the unit itself: a file
//! in the user's systemd configuration that runs the installed xremap
//! with Keyloom's generated configuration, told which desktop to ask
//! for application-specific rules when the binary understands that.

use std::fmt;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use tokio::process::Command;

use crate::session::Desktop;
use crate::xremap;

/// The systemd user unit Keyloom manages.
pub const UNIT: &str = "xremap.service";

/// First line of the unit file Keyloom installs. A unit without it
/// belongs to the user and is backed up before being replaced, never
/// silently overwritten.
pub const UNIT_MARKER: &str =
    "# Generated by Keyloom. Do not edit by hand; Keyloom overwrites this file.";

/// Whether remapping should be running: the status chip's two
/// positions, and what a switch still in flight is heading for.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Remapping {
    On,
    Off,
}

/// Why a `systemctl` command did not do what Keyloom asked.
///
/// Held in a [`crate::app::Message`], which must be `Clone`, so the
/// underlying [`io::Error`] is shared rather than copied.
#[derive(Clone, Debug)]
pub enum Error {
    /// `systemctl` could not be run at all.
    Unavailable(Arc<io::Error>),
    /// It ran and refused; the text is systemd's own explanation.
    Refused(String),
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Unavailable(err) => write!(f, "could not run systemctl: {err}"),
            Self::Refused(message) => f.write_str(message),
        }
    }
}

impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Unavailable(err) => Some(&**err),
            Self::Refused(_) => None,
        }
    }
}

/// State of the xremap user service, as far as systemd knows.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Status {
    /// The unit is loaded and running.
    Active,
    /// The unit exists but is not running.
    Inactive,
    /// The unit exists and its last run failed.
    Failed,
    /// No `xremap.service` user unit is registered.
    NotFound,
    /// `systemctl` is unavailable (not a systemd session).
    Unavailable,
}

impl Status {
    /// User-facing state label. xremap and systemd are implementation
    /// details, so the wording stays generic.
    pub fn label(self) -> &'static str {
        match self {
            Self::Active => "Remapping Enabled",
            // A stopped unit is a paused one, however it came to be
            // stopped: the distinction is Keyloom's, not the user's.
            Self::Inactive => "Remapping Paused",
            Self::Failed => "Remapping Failed",
            Self::NotFound => "Remapping not set up",
            Self::Unavailable => "Remapping Unavailable",
        }
    }
}

/// What `systemctl --user show` reports about the unit.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Unit {
    /// Whether it runs, or exists at all.
    pub status: Status,
    /// Whether the unit starts with the graphical session.
    pub enabled: bool,
    /// The unit file systemd loaded, when it found one.
    pub fragment_path: Option<PathBuf>,
}

impl Unit {
    const UNAVAILABLE: Self = Self {
        status: Status::Unavailable,
        enabled: false,
        fragment_path: None,
    };
}

/// Query the unit. `show` succeeds even for missing units, reporting
/// `LoadState=not-found`, which keeps the cases apart.
pub async fn inspect() -> Unit {
    let output = Command::new("systemctl")
        .args([
            "--user",
            "show",
            UNIT,
            "--property=LoadState,ActiveState,UnitFileState,FragmentPath",
        ])
        .output()
        .await;
    match output {
        Ok(output) if output.status.success() => {
            parse_show(&String::from_utf8_lossy(&output.stdout))
        }
        _ => Unit::UNAVAILABLE,
    }
}

/// Query the unit's state alone.
pub async fn status() -> Status {
    inspect().await.status
}

/// Read the `key=value` lines `systemctl show` prints.
fn parse_show(stdout: &str) -> Unit {
    let property = |name: &str| {
        stdout
            .lines()
            .find_map(|line| line.strip_prefix(name)?.strip_prefix('='))
    };
    if property("LoadState") == Some("not-found") {
        return Unit {
            status: Status::NotFound,
            enabled: false,
            fragment_path: None,
        };
    }
    let status = match property("ActiveState") {
        Some("active" | "activating" | "reloading") => Status::Active,
        Some("failed") => Status::Failed,
        _ => Status::Inactive,
    };
    Unit {
        status,
        enabled: matches!(
            property("UnitFileState"),
            Some("enabled" | "enabled-runtime")
        ),
        fragment_path: property("FragmentPath")
            .filter(|path| !path.is_empty())
            .map(PathBuf::from),
    }
}

/// Where Keyloom installs its unit:
/// `$XDG_CONFIG_HOME/systemd/user/xremap.service` (usually `~/.config`),
/// which systemd reads ahead of anything a package installed.
pub fn unit_path() -> Option<PathBuf> {
    Some(
        xremap::config_home()?
            .join("systemd")
            .join("user")
            .join(UNIT),
    )
}

/// Waits for the compositor's Wayland socket before xremap starts,
/// up to 30 seconds. The graphical session target can be reached
/// before the socket exists, and xremap connects to the compositor
/// for application-specific rules.
const WAIT_FOR_WAYLAND: &str = "/bin/sh -c 'for i in $(seq 1 30); do \
                                ls $XDG_RUNTIME_DIR/wayland-* >/dev/null 2>&1 && exit 0; \
                                sleep 1; done; exit 1'";

/// How the unit starts xremap, beyond the binary and the configuration.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Launch {
    /// The desktop xremap should ask which window is in front, passed
    /// as `--desktop`. `None` leaves the choice to xremap, which is
    /// also all that a binary older than 0.15.13 understands.
    pub desktop: Option<Desktop>,
    /// Wait for the compositor's Wayland socket before starting. On an
    /// X11 session the socket never appears, so the wait would only
    /// keep the unit from ever starting.
    pub wait_for_wayland: bool,
}

impl Default for Launch {
    /// A Wayland session with the desktop left to xremap: the unit as
    /// Keyloom always installed it.
    fn default() -> Self {
        Self {
            desktop: None,
            wait_for_wayland: true,
        }
    }
}

/// The unit file Keyloom installs, modeled on a hand-written unit that
/// has run xremap on COSMIC for a long time: run the given xremap
/// binary with Keyloom's generated configuration, follow keyboards as
/// they are plugged in, live with the graphical session, wait for the
/// compositor before starting (on Wayland), and keep xremap running.
///
/// Logging stays at `info`: xremap's `debug` level writes every key
/// press to the journal.
pub fn unit_file(binary: &Path, config: &Path, launch: Launch) -> String {
    let wait = if launch.wait_for_wayland {
        format!("ExecStartPre={WAIT_FOR_WAYLAND}\n")
    } else {
        String::new()
    };
    let desktop = launch.desktop.map_or_else(String::new, |desktop| {
        format!("  --desktop {} \\\n", desktop.flag())
    });
    format!(
        "{UNIT_MARKER}\n\
         [Unit]\n\
         Description=Keyboard remapping for Keyloom (xremap)\n\
         Documentation={}\n\
         After=graphical-session.target input-method.target\n\
         PartOf=graphical-session.target\n\
         \n\
         [Service]\n\
         Restart=always\n\
         RestartSec=5\n\
         {wait}\
         Environment=RUST_LOG=info\n\
         ExecStart={} \\\n\
         {desktop}\
         \x20 --watch \\\n\
         \x20 {}\n\
         \n\
         [Install]\n\
         WantedBy=graphical-session.target\n",
        env!("CARGO_PKG_REPOSITORY"),
        quote(binary),
        quote(config)
    )
}

/// Quote a path for a unit's command line the way systemd expects:
/// double quotes with backslash escapes, and only when needed.
fn quote(path: &Path) -> String {
    let path = path.to_string_lossy();
    if !path.is_empty()
        && !path
            .chars()
            .any(|c| c.is_whitespace() || matches!(c, '"' | '\'' | '\\' | ';'))
    {
        return path.into_owned();
    }
    let mut quoted = String::with_capacity(path.len() + 2);
    quoted.push('"');
    for c in path.chars() {
        if matches!(c, '"' | '\\') {
            quoted.push('\\');
        }
        quoted.push(c);
    }
    quoted.push('"');
    quoted
}

/// Result of installing the unit file.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum InstallOutcome {
    /// File created or replaced; systemd has to reload to see it.
    Written,
    /// File already had exactly this content.
    Unchanged,
}

/// Write the unit file to [`unit_path`]. A file there that Keyloom did
/// not write is backed up beside it first.
///
/// # Errors
///
/// When there is no home directory or the file cannot be written.
pub fn install(text: &str) -> io::Result<InstallOutcome> {
    let path = unit_path().ok_or_else(|| {
        io::Error::new(io::ErrorKind::NotFound, "no home directory to write into")
    })?;
    install_to(&path, text)
}

/// [`install`] with an explicit target path.
///
/// # Errors
///
/// When an existing foreign file cannot be backed up, or the directory
/// or file cannot be written.
pub fn install_to(path: &Path, text: &str) -> io::Result<InstallOutcome> {
    if let Ok(existing) = fs::read_to_string(path) {
        if existing == text {
            return Ok(InstallOutcome::Unchanged);
        }
        if !existing.starts_with(UNIT_MARKER) {
            xremap::backup(path)?;
        }
    }
    let dir = path
        .parent()
        .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidInput, "unit path has no parent"))?;
    fs::create_dir_all(dir)?;
    let tmp = path.with_extension("service.tmp");
    fs::write(&tmp, text)?;
    fs::rename(&tmp, path)?;
    Ok(InstallOutcome::Written)
}

/// Make systemd read unit files again, after installing one.
///
/// # Errors
///
/// As [`restart`].
pub async fn daemon_reload() -> Result<(), Error> {
    run(&["daemon-reload"]).await
}

/// Start the unit with every graphical session from now on.
///
/// # Errors
///
/// As [`restart`].
pub async fn enable() -> Result<(), Error> {
    run(&["enable", UNIT]).await
}

/// Restart the unit so xremap picks up the generated configuration.
///
/// # Errors
///
/// Fails when `systemctl` cannot be run, or when systemd refuses the
/// restart (a missing unit, a start rate limit, a failing `ExecStart`).
pub async fn restart() -> Result<(), Error> {
    run(&["restart", UNIT]).await
}

/// Put remapping in the requested state: stopping the unit releases the
/// keyboards xremap grabbed, so they can be observed directly. Only the
/// status chip asks for this.
///
/// # Errors
///
/// As [`restart`]. Starting an already-running unit, or stopping an
/// already-stopped one, succeeds without doing anything.
pub async fn set(remapping: Remapping) -> Result<(), Error> {
    run(&[
        match remapping {
            Remapping::On => "start",
            Remapping::Off => "stop",
        },
        UNIT,
    ])
    .await
}

/// Run one `systemctl --user` command.
async fn run(args: &[&str]) -> Result<(), Error> {
    let output = Command::new("systemctl")
        .arg("--user")
        .args(args)
        .output()
        .await
        .map_err(|err| Error::Unavailable(Arc::new(err)))?;
    if output.status.success() {
        return Ok(());
    }
    let stderr = String::from_utf8_lossy(&output.stderr);
    let stderr = stderr.trim();
    Err(Error::Refused(if stderr.is_empty() {
        format!("systemctl exited with {}", output.status)
    } else {
        stderr.to_owned()
    }))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testing::TempDir;

    #[test]
    fn show_output_is_parsed_into_a_unit() {
        assert_eq!(
            parse_show(
                "LoadState=not-found\nActiveState=inactive\nUnitFileState=\nFragmentPath=\n"
            ),
            Unit {
                status: Status::NotFound,
                enabled: false,
                fragment_path: None,
            }
        );
        assert_eq!(
            parse_show(
                "LoadState=loaded\nActiveState=active\nUnitFileState=enabled\nFragmentPath=/home/me/.config/systemd/user/xremap.service\n"
            ),
            Unit {
                status: Status::Active,
                enabled: true,
                fragment_path: Some(PathBuf::from(
                    "/home/me/.config/systemd/user/xremap.service"
                )),
            }
        );
        let failed = parse_show("LoadState=loaded\nActiveState=failed\nUnitFileState=disabled\n");
        assert_eq!(failed.status, Status::Failed);
        assert!(!failed.enabled);
        assert_eq!(failed.fragment_path, None);
        assert_eq!(
            parse_show("LoadState=loaded\nActiveState=activating\n").status,
            Status::Active
        );
        assert_eq!(parse_show("").status, Status::Inactive);
    }

    #[test]
    fn the_unit_runs_xremap_on_the_generated_config() {
        let unit = unit_file(
            Path::new("/usr/bin/xremap"),
            Path::new("/home/me/.config/xremap/keyloom.yml"),
            Launch::default(),
        );
        assert!(unit.starts_with(&format!("{UNIT_MARKER}\n[Unit]\n")));
        assert!(unit.contains(
            "\nExecStart=/usr/bin/xremap \\\n  --watch \\\n  /home/me/.config/xremap/keyloom.yml\n"
        ));
        assert_eq!(
            crate::setup::exec_start_of(&unit),
            "/usr/bin/xremap --watch /home/me/.config/xremap/keyloom.yml",
            "continuation lines join back into one command"
        );
        assert!(unit.contains("\nRestartSec=5\nExecStartPre=/bin/sh -c 'for i in $(seq 1 30); do ls $XDG_RUNTIME_DIR/wayland-* >/dev/null 2>&1 && exit 0; sleep 1; done; exit 1'\nEnvironment=RUST_LOG=info\n"));
        assert!(unit.contains("\nRestart=always\n"));
        assert!(unit.contains("\nWantedBy=graphical-session.target\n"));
        assert!(unit.contains("\nPartOf=graphical-session.target\n"));
        assert!(unit.contains("\nAfter=graphical-session.target input-method.target\n"));
        assert!(
            !unit.contains("--desktop"),
            "the desktop is left to xremap by default"
        );
        assert_eq!(
            unit,
            unit_file(
                Path::new("/usr/bin/xremap"),
                Path::new("/home/me/.config/xremap/keyloom.yml"),
                Launch::default(),
            ),
            "generation is deterministic"
        );
    }

    #[test]
    fn the_unit_names_the_desktop_when_asked_to() {
        let unit = unit_file(
            Path::new("/home/me/.local/bin/xremap"),
            Path::new("/home/me/.config/xremap/keyloom.yml"),
            Launch {
                desktop: Some(Desktop::Cosmic),
                wait_for_wayland: true,
            },
        );
        assert!(unit.contains(
            "\nExecStart=/home/me/.local/bin/xremap \\\n  --desktop cosmic \\\n  --watch \\\n  /home/me/.config/xremap/keyloom.yml\n"
        ));
        assert_eq!(
            crate::setup::exec_start_of(&unit),
            "/home/me/.local/bin/xremap --desktop cosmic --watch /home/me/.config/xremap/keyloom.yml",
            "the flag comes before the config, which xremap takes positionally"
        );
        assert!(unit.contains("\nExecStartPre="));
    }

    #[test]
    fn x11_sessions_do_not_wait_for_a_wayland_socket() {
        let unit = unit_file(
            Path::new("/usr/bin/xremap"),
            Path::new("/home/me/.config/xremap/keyloom.yml"),
            Launch {
                desktop: Some(Desktop::X11),
                wait_for_wayland: false,
            },
        );
        assert!(
            !unit.contains("ExecStartPre="),
            "nothing to wait for on X11"
        );
        assert!(unit.contains("\nRestartSec=5\nEnvironment=RUST_LOG=info\nExecStart=/usr/bin/xremap \\\n  --desktop x11 \\\n"));
        assert!(unit.starts_with(UNIT_MARKER));
    }

    #[test]
    fn paths_with_awkward_characters_are_quoted() {
        assert_eq!(quote(Path::new("/usr/bin/xremap")), "/usr/bin/xremap");
        assert_eq!(
            quote(Path::new("/home/my user/keyloom.yml")),
            "\"/home/my user/keyloom.yml\""
        );
        assert_eq!(
            quote(Path::new("/home/a\"b/c\\d.yml")),
            "\"/home/a\\\"b/c\\\\d.yml\""
        );
        assert_eq!(quote(Path::new("")), "\"\"");
    }

    #[test]
    fn installing_backs_up_foreign_units_but_not_our_own() {
        let dir = TempDir::new("service-install");
        let path = dir.path().join("systemd").join("user").join(UNIT);
        let ours = unit_file(
            Path::new("/usr/bin/xremap"),
            Path::new("/home/me/keyloom.yml"),
            Launch::default(),
        );

        assert_eq!(install_to(&path, &ours).unwrap(), InstallOutcome::Written);
        assert_eq!(fs::read_to_string(&path).unwrap(), ours);
        assert_eq!(install_to(&path, &ours).unwrap(), InstallOutcome::Unchanged);

        // Our own unit is rewritten in place.
        let updated = unit_file(
            Path::new("/usr/local/bin/xremap"),
            Path::new("/home/me/keyloom.yml"),
            Launch::default(),
        );
        assert_eq!(
            install_to(&path, &updated).unwrap(),
            InstallOutcome::Written
        );
        assert!(!path.with_file_name(format!("{UNIT}.bak")).exists());

        // Someone else's unit is kept beside the replacement.
        let theirs = "[Service]\nExecStart=/usr/bin/xremap /home/me/mine.yml\n";
        fs::write(&path, theirs).unwrap();
        assert_eq!(install_to(&path, &ours).unwrap(), InstallOutcome::Written);
        assert_eq!(fs::read_to_string(&path).unwrap(), ours);
        assert_eq!(
            fs::read_to_string(path.with_file_name(format!("{UNIT}.bak"))).unwrap(),
            theirs
        );
        assert!(!path.with_extension("service.tmp").exists());
    }

    #[test]
    fn the_unit_lives_in_the_user_configuration() {
        let path = unit_path().expect("a home directory");
        assert!(path.ends_with(Path::new("systemd/user").join(UNIT)));
        assert!(path.is_absolute());
    }
}
