//! Translation layer from Keyloom's internal mapping model to a valid
//! xremap configuration file.
//!
//! The rule model in [`crate::ui::model`] is the source of truth; the
//! YAML written to the user's config directory is generated output.
//! Generation is deterministic: identical mappings always produce
//! byte-identical YAML, with sources sorted by their xremap key name.
//!
//! Mappings become `modmap` entries, one block per scope (an
//! application scope, a keyboard, both, or neither), most specific
//! first. Layers become `keymap` rules guarded by a virtual modifier
//! that stands in for the held layer key (see [`LAYER_MODIFIERS`]), and
//! shortcut groups become `keymap` rules of their own.

use std::collections::{BTreeMap, HashMap};
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use evdev::KeyCode;

use crate::ui::model::{self, AppScope, Chord, Group, Layer, Mapping, Maps, ModifierSide};

/// First line of every file Keyloom generates. Files that don't start
/// with this marker are treated as foreign and never silently replaced.
const MARKER: &str = "# Generated by Keyloom. Do not edit by hand; Keyloom overwrites this file.";

/// Stand-ins for held layer keys. xremap treats a key listed under
/// `virtual_modifiers` as a modifier for `keymap` rules and never sends
/// it on, so each layer's key is remapped to one of these and the
/// layer's rules match on it. Braille-dot codes are used because no
/// keyboard emits them: nothing but the layer key can activate a layer.
/// The pool caps how many layers a profile can generate rules for.
const LAYER_MODIFIERS: [&str; 10] = [
    "KEY_BRL_DOT1",
    "KEY_BRL_DOT2",
    "KEY_BRL_DOT3",
    "KEY_BRL_DOT4",
    "KEY_BRL_DOT5",
    "KEY_BRL_DOT6",
    "KEY_BRL_DOT7",
    "KEY_BRL_DOT8",
    "KEY_BRL_DOT9",
    "KEY_BRL_DOT10",
];

/// How many layers one profile can generate rules for.
pub const MAX_LAYERS: usize = LAYER_MODIFIERS.len();

/// Whether a deck key is one of the physical modifiers (Shift, Control,
/// Alt, Super). xremap always passes those through, so they cannot take
/// on a job inside a layer.
pub fn is_modifier_key(code: &str) -> bool {
    const MODIFIERS: [KeyCode; 8] = [
        KeyCode::KEY_LEFTSHIFT,
        KeyCode::KEY_RIGHTSHIFT,
        KeyCode::KEY_LEFTCTRL,
        KeyCode::KEY_RIGHTCTRL,
        KeyCode::KEY_LEFTALT,
        KeyCode::KEY_RIGHTALT,
        KeyCode::KEY_LEFTMETA,
        KeyCode::KEY_RIGHTMETA,
    ];
    model::key(code).is_some_and(|cap| MODIFIERS.contains(&KeyCode(cap.evdev)))
}

/// xremap key name (`KEY_*`) for a physical key on the deck, derived
/// from its evdev scancode.
pub fn key_symbol(code: &str) -> Option<String> {
    model::key(code).and_then(|cap| evdev_name(cap.evdev))
}

/// xremap key name (`KEY_*`) for an action from the editor's catalog
/// (e.g. `Escape`, `Right Control`, `Play/Pause`).
///
/// Returns `None` for actions with no evdev key, such as `Hyper` and
/// `Disabled` (the generator handles `Disabled` itself).
pub fn action_symbol(action: &str) -> Option<String> {
    // Actions named after a physical key ("Caps Lock", "Right Control",
    // "Numpad 7", "ISO Backslash", …) resolve through its scancode.
    if let Some(cap) = model::registry().find(|cap| model::key_name(cap.code) == action) {
        return evdev_name(cap.evdev);
    }
    // Older generic names still accepted from stored mappings.
    const ACTIONS: &[(&str, &str)] = &[
        ("Control", "KEY_LEFTCTRL"),
        ("Shift", "KEY_LEFTSHIFT"),
        ("Alt", "KEY_LEFTALT"),
        ("Super", "KEY_LEFTMETA"),
        ("Left", "KEY_LEFT"),
        ("Right", "KEY_RIGHT"),
        ("Up", "KEY_UP"),
        ("Down", "KEY_DOWN"),
        ("Bracket Left", "KEY_LEFTBRACE"),
        ("Bracket Right", "KEY_RIGHTBRACE"),
    ];
    ACTIONS
        .iter()
        .find(|(name, _)| *name == action)
        .map(|(_, symbol)| (*symbol).to_owned())
}

/// Canonical evdev name for a scancode (`KEY_CAPSLOCK`), which xremap
/// accepts directly. `None` for codes evdev has no name for.
fn evdev_name(scancode: u16) -> Option<String> {
    let name = format!("{:?}", KeyCode(scancode));
    name.starts_with("KEY_").then_some(name)
}

/// Everything of one profile the generator reads.
#[derive(Clone, Copy, Debug)]
pub struct Rules<'a> {
    pub maps: &'a Maps,
    pub layers: &'a [Layer],
    pub apps: &'a [AppScope],
    pub groups: &'a [Group],
}

/// An application scope as a block filter: the scope's name and id,
/// and every application id xremap should match.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct AppAxis {
    name: String,
    id: String,
    matchers: Vec<String>,
}

/// A keyboard as a block filter: xremap matches on the resolved name.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct DeviceAxis {
    name: String,
    id: String,
}

/// Where a block applies: an application scope or every application,
/// and one keyboard or every keyboard.
///
/// Scopes order most specific first (see [`model::scope_rank`]), which
/// is the order blocks are written in: xremap uses the first block that
/// mentions a key and whose filters match, so an application's block
/// has to come before a keyboard's, and both before the general one.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Scope {
    rank: u8,
    app: Option<AppAxis>,
    device: Option<DeviceAxis>,
}

impl Scope {
    fn new(app: Option<AppAxis>, device: Option<DeviceAxis>) -> Self {
        Self {
            rank: model::scope_rank(device.is_none(), app.is_none()),
            app,
            device,
        }
    }

    /// Every keyboard in every application.
    fn general() -> Self {
        Self::new(None, None)
    }

    /// Where both scopes apply, or `None` when they never overlap.
    fn intersect(&self, other: &Self) -> Option<Self> {
        fn axis<T: Clone + PartialEq>(a: &Option<T>, b: &Option<T>) -> Option<Option<T>> {
            match (a, b) {
                (None, either) | (either, None) => Some(either.clone()),
                (Some(a), Some(b)) => (a == b).then(|| Some(a.clone())),
            }
        }
        Some(Self::new(
            axis(&self.app, &other.app)?,
            axis(&self.device, &other.device)?,
        ))
    }

    /// The scope's places, for block titles:
    /// ` (COSMIC Terminal, Keychron K2 Pro)`.
    fn suffix(&self) -> String {
        let names: Vec<&str> = self
            .app
            .iter()
            .map(|app| app.name.as_str())
            .chain(self.device.iter().map(|device| device.name.as_str()))
            .collect();
        if names.is_empty() {
            String::new()
        } else {
            format!(" ({})", names.join(", "))
        }
    }

    /// The block's `application` and `device` filters.
    fn filters(&self) -> String {
        let mut filters = String::new();
        if let Some(app) = &self.app {
            let ids: Vec<String> = app.matchers.iter().map(|id| quote(id)).collect();
            filters.push_str(&format!(
                "    application:\n      only: [{}]\n",
                ids.join(", ")
            ));
        }
        if let Some(device) = &self.device {
            filters.push_str(&format!(
                "    device:\n      only: [{}]\n",
                quote(&device.name)
            ));
        }
        filters
    }
}

/// Resolves the scope ids stored with mappings, jobs, and groups.
struct Places<'a, F> {
    apps: &'a [AppScope],
    device_name: F,
}

impl<F: Fn(&str) -> String> Places<'_, F> {
    /// The scope for a device id and an application scope id, or
    /// `None` when nothing can apply there: the application scope no
    /// longer exists, or it has no applications.
    fn scope(&self, device: &str, app: &str) -> Option<Scope> {
        let app = if app.is_empty() {
            None
        } else {
            let scope = self.apps.iter().find(|scope| scope.id == app)?;
            let matchers: Vec<String> = scope.matchers().into_iter().map(str::to_owned).collect();
            if matchers.is_empty() {
                return None;
            }
            Some(AppAxis {
                name: scope.name.clone(),
                id: scope.id.clone(),
                matchers,
            })
        };
        let device = (!model::every_device(device)).then(|| DeviceAxis {
            name: (self.device_name)(device),
            id: device.to_owned(),
        });
        Some(Scope::new(app, device))
    }
}

/// What a source key produces in the generated modmap.
#[derive(Clone, Debug, PartialEq, Eq)]
enum Output {
    /// Simple remap to one key.
    Key(String),
    /// Key emits nothing (`Disabled` in the editor).
    Disabled,
    /// Tap/hold multi-purpose key. `None` slots emit nothing.
    TapHold {
        alone: Option<String>,
        held: Option<String>,
    },
}

/// What a mapping slot turns into: `Some(None)` disables it,
/// `Some(Some(_))` remaps it, and `None` leaves it alone because it is
/// unset or holds an untranslatable action (e.g. `Hyper`).
fn slot(action: Option<&str>) -> Option<Option<String>> {
    match action {
        Some("Disabled") => Some(None),
        Some(action) => action_symbol(action).map(Some),
        None => None,
    }
}

/// Resolve one mapping into `(source symbol, output)`, or `None` when
/// nothing about it can be expressed as an xremap rule.
///
/// A "normal here" mapping maps the key to itself: listed ahead of the
/// more general blocks, that keeps the key as it is in its scope, and
/// keeps a layer the key holds from activating there.
///
/// A key that holds a layer produces the layer's modifier while held:
/// its tap action keeps working through a tap/hold key, and any hold
/// action is superseded by the layer.
fn resolve(
    code: &str,
    mapping: &Mapping,
    layer_modifier: Option<&str>,
) -> Option<(String, Output)> {
    let source = key_symbol(code)?;
    if mapping.normal {
        return Some((source.clone(), Output::Key(source)));
    }
    let tap = slot(mapping.tap.as_deref());
    let output = if let Some(modifier) = layer_modifier {
        match tap {
            Some(Some(key)) => Output::TapHold {
                alone: Some(key),
                held: Some(modifier.to_owned()),
            },
            _ => Output::Key(modifier.to_owned()),
        }
    } else {
        match slot(mapping.hold.as_deref()) {
            Some(held) => Output::TapHold {
                // Tapping falls back to the key's own behavior when only
                // a hold action is configured (xremap requires `alone`).
                alone: tap.unwrap_or(Some(source.clone())),
                held,
            },
            None => match tap {
                Some(None) => Output::Disabled,
                Some(Some(key)) => Output::Key(key),
                None => return None,
            },
        }
    };
    Some((source, output))
}

/// Layer key code → the modifier standing in for it.
type Triggers<'a> = HashMap<&'a str, &'static str>;

/// Entries for one scope, sorted by source symbol.
fn scope_entries(mappings: &[&(String, Mapping)], triggers: &Triggers) -> BTreeMap<String, Output> {
    let mut entries = BTreeMap::new();
    // Explicit mappings first; the model keeps one mapping per key and
    // scope.
    for (code, mapping) in mappings {
        let modifier = triggers.get(code.as_str()).copied();
        if let Some((source, output)) = resolve(code, mapping, modifier) {
            entries.entry(source).or_insert(output);
        }
    }
    // Two-way swaps add the reverse entry unless the reverse source
    // already has an explicit mapping.
    for (code, mapping) in mappings {
        if !mapping.swap || mapping.hold.is_some() || mapping.normal {
            continue;
        }
        let (Some(source), Some(tap)) = (key_symbol(code), mapping.tap.as_deref()) else {
            continue;
        };
        if let Some(reverse) = action_symbol(tap)
            && reverse != source
        {
            entries.entry(reverse).or_insert(Output::Key(source));
        }
    }
    entries
}

/// Single-quote a YAML scalar (device names may contain anything).
fn quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

/// The `name:` line of a block, plus its filters for a specific
/// application scope or keyboard.
fn block_header(title: &str, scope: &Scope) -> String {
    format!(
        "  - name: {}\n{}",
        quote(&format!("{title}{}", scope.suffix())),
        scope.filters()
    )
}

/// One `modmap` block.
fn modmap_block(scope: &Scope, entries: &BTreeMap<String, Output>) -> String {
    let mut block = block_header("Keyloom mappings", scope);
    block.push_str("    remap:\n");
    for (source, output) in entries {
        match output {
            Output::Key(key) => block.push_str(&format!("      {source}: {key}\n")),
            Output::Disabled => block.push_str(&format!("      {source}: []\n")),
            Output::TapHold { alone, held } => {
                let slot = |slot: &Option<String>| slot.clone().unwrap_or_else(|| "[]".to_owned());
                block.push_str(&format!("      {source}:\n"));
                block.push_str(&format!("        held: {}\n", slot(held)));
                block.push_str(&format!("        alone: {}\n", slot(alone)));
            }
        }
    }
    block
}

/// A layer whose key is a known deck key, with the modifier standing
/// in for it.
struct ResolvedLayer<'a> {
    layer: &'a Layer,
    /// The layer key's own symbol.
    trigger: String,
    modifier: &'static str,
}

/// Layers that can generate rules, in profile order. Layers whose key
/// is unset or unknown, and layers beyond the modifier pool, are left
/// out.
fn resolve_layers(layers: &[Layer]) -> Vec<ResolvedLayer<'_>> {
    layers
        .iter()
        .filter_map(|layer| key_symbol(&layer.trigger).map(|trigger| (layer, trigger)))
        .zip(LAYER_MODIFIERS)
        .map(|((layer, trigger), modifier)| ResolvedLayer {
            layer,
            trigger,
            modifier,
        })
        .collect()
}

/// The symbol a key arrives at the rules as once its mapping ran:
/// `None` when the tap is disabled and the key never arrives. A
/// hold-only, untranslatable, or "normal here" mapping leaves the key
/// as itself.
fn arrives_as(source: &str, mapping: &Mapping) -> Option<String> {
    if mapping.normal {
        return Some(source.to_owned());
    }
    match slot(mapping.tap.as_deref()) {
        Some(None) => None,
        Some(Some(key)) => Some(key),
        None => Some(source.to_owned()),
    }
}

/// The symbol a job's key arrives at the rules with, in the job's scope
/// and in every narrower scope where a mapping changes it. Mappings run
/// first, so a job on a remapped key has to match what the key became:
/// the most specific mapping covering the whole job scope sets the base
/// rule, and a mapping overlapping only part of it (the key remapped on
/// one keyboard, or in one application) adds a rule for that part. A
/// symbol of `None` means the key never arrives there.
fn rule_sources<F: Fn(&str) -> String>(
    code: &str,
    job: &Scope,
    maps: &Maps,
    places: &Places<'_, F>,
) -> Vec<(Scope, Option<String>)> {
    let Some(source) = key_symbol(code) else {
        return Vec::new();
    };
    // The most specific mapping covering the job's whole scope, as
    // (rank, symbol).
    let mut base: Option<(u8, Option<String>)> = None;
    // Per partial overlap, the most specific mapping there.
    let mut refinements: BTreeMap<Scope, (u8, Option<String>)> = BTreeMap::new();
    for (_, mapping) in maps.iter().filter(|(key, _)| key == code) {
        let Some(scope) = places.scope(&mapping.device, &mapping.app) else {
            continue;
        };
        let Some(overlap) = scope.intersect(job) else {
            continue;
        };
        let symbol = arrives_as(&source, mapping);
        if overlap == *job {
            if base.as_ref().is_none_or(|(rank, _)| scope.rank < *rank) {
                base = Some((scope.rank, symbol));
            }
        } else {
            let entry = refinements.entry(overlap).or_insert((u8::MAX, None));
            if scope.rank < entry.0 {
                *entry = (scope.rank, symbol);
            }
        }
    }
    let base = base.map_or_else(|| Some(source.clone()), |(_, symbol)| symbol);
    let mut sources = vec![(job.clone(), base.clone())];
    // A part where the key arrives as it does in the base rule, or not
    // at all, needs no rule of its own.
    sources.extend(
        refinements
            .into_iter()
            .filter(|(_, (_, symbol))| symbol.is_some() && *symbol != base)
            .map(|(scope, (_, symbol))| (scope, symbol)),
    );
    sources
}

/// The `keymap` blocks for one layer, one per scope.
fn layer_blocks<F: Fn(&str) -> String>(
    layer: &ResolvedLayer<'_>,
    maps: &Maps,
    triggers: &Triggers,
    places: &Places<'_, F>,
) -> Vec<String> {
    // Source symbol → output (`None` emits nothing), per scope.
    let mut rules: BTreeMap<Scope, BTreeMap<String, Option<String>>> = BTreeMap::new();
    for key in &layer.layer.keys {
        // A layer key is remapped before the rules see it, and physical
        // modifiers always pass through: neither can take a job.
        if triggers.contains_key(key.code.as_str()) || is_modifier_key(&key.code) {
            continue;
        }
        let output = match key.action.as_str() {
            "Disabled" => None,
            action => match action_symbol(action) {
                Some(symbol) => Some(symbol),
                None => continue,
            },
        };
        let Some(scope) = places.scope(&key.device, &key.app) else {
            continue;
        };
        for (scope, source) in rule_sources(&key.code, &scope, maps, places) {
            let Some(source) = source else {
                continue;
            };
            rules
                .entry(scope)
                .or_default()
                .entry(source)
                .or_insert_with(|| output.clone());
        }
    }

    let title = format!(
        "Keyloom layer: {}, hold {}",
        layer.layer.name,
        model::key_name(&layer.layer.trigger)
    );
    rules
        .iter()
        .filter(|(_, rules)| !rules.is_empty())
        .map(|(scope, rules)| {
            let mut block = block_header(&title, scope);
            block.push_str("    remap:\n");
            for (source, output) in rules {
                let modifier = layer.modifier;
                match output {
                    Some(key) => block.push_str(&format!("      {modifier}-{source}: {key}\n")),
                    None => block.push_str(&format!("      {modifier}-{source}: []\n")),
                }
            }
            block
        })
        .collect()
}

/// xremap's name for a chord modifier: the alias that matches either
/// key for a side-less one, the key itself for a sided one. Unknown
/// names (the design's "Any") are left out of a chord.
fn modifier_symbol(name: &str) -> Option<&'static str> {
    const KEYS: [[&str; 2]; 4] = [
        ["KEY_LEFTCTRL", "KEY_RIGHTCTRL"],
        ["KEY_LEFTSHIFT", "KEY_RIGHTSHIFT"],
        ["KEY_LEFTALT", "KEY_RIGHTALT"],
        ["KEY_LEFTMETA", "KEY_RIGHTMETA"],
    ];
    let (family, side) = model::parse_modifier(name)?;
    Some(match side {
        ModifierSide::Either => model::MODS[family],
        ModifierSide::Left => KEYS[family][0],
        ModifierSide::Right => KEYS[family][1],
    })
}

/// A chord in xremap's `Mod-Mod-KEY` form, or `None` when its key has
/// no xremap name (an empty chord, or `Hyper`).
fn chord_symbol(chord: &Chord) -> Option<String> {
    let key = action_symbol(&chord.key)?;
    let mut parts: Vec<&str> = chord
        .mods
        .iter()
        .filter_map(|name| modifier_symbol(name))
        .collect();
    parts.push(&key);
    Some(parts.join("-"))
}

/// The `keymap` blocks for the shortcut groups: groups limited to an
/// application first, then the general ones, each in profile order, so
/// a shortcut made for an application wins over the same shortcut made
/// for every application. Paused groups, incomplete rules, and rules
/// with keys xremap cannot name generate nothing. A rule whose two
/// sides are the same changes nothing by itself and is left out, so
/// the key keeps passing through (repeats included); with "any
/// modifier" it still adds the entries that drop a held modifier.
fn group_blocks<F: Fn(&str) -> String>(groups: &[Group], places: &Places<'_, F>) -> Vec<String> {
    let mut blocks: Vec<(u8, String)> = Vec::new();
    for group in groups.iter().filter(|group| group.enabled) {
        let Some(scope) = places.scope("all", &group.scope) else {
            continue;
        };
        let mut lines = String::new();
        // The same chord twice in a group would be a duplicate YAML key.
        let mut seen: Vec<String> = Vec::new();
        let mut rule_line = |from: String, to: &str| {
            if !seen.contains(&from) {
                lines.push_str(&format!("      {from}: {to}\n"));
                seen.push(from);
            }
        };
        for rule in group.rules.iter().filter(|rule| rule.is_complete()) {
            let (Some(from), Some(to)) = (chord_symbol(&rule.from), chord_symbol(&rule.to)) else {
                continue;
            };
            // "Any modifier": the chord also matches with each other
            // modifier held, which xremap then releases around the
            // output instead of passing it through.
            if group.any_mod {
                for (family, modifier) in model::MODS.iter().enumerate() {
                    let held = rule.from.mods.iter().any(|held| {
                        model::parse_modifier(held).is_some_and(|(held, _)| held == family)
                    });
                    if !held {
                        rule_line(format!("{modifier}-{from}"), &to);
                    }
                }
            }
            if from != to {
                rule_line(from, &to);
            }
        }
        if lines.is_empty() {
            continue;
        }
        let mut block = block_header(&format!("Keyloom shortcuts: {}", group.name), &scope);
        block.push_str("    remap:\n");
        block.push_str(&lines);
        blocks.push((scope.rank, block));
    }
    blocks.sort_by_key(|(rank, _)| *rank);
    blocks.into_iter().map(|(_, block)| block).collect()
}

/// Render a profile's mappings, layers, and shortcut groups as a
/// complete xremap document.
///
/// `device_name` resolves a device scope id to the display name xremap
/// should match on. Blocks are written most specific scope first: an
/// application scope's block, then a keyboard's, then the general one
/// (see [`Scope`]).
pub fn generate(rules: Rules<'_>, device_name: impl Fn(&str) -> String) -> String {
    let places = Places {
        apps: rules.apps,
        device_name,
    };
    let layers = resolve_layers(rules.layers);
    let triggers: Triggers = layers
        .iter()
        .map(|layer| (layer.layer.trigger.as_str(), layer.modifier))
        .collect();

    // Group mappings by scope. A mapping whose application scope is
    // gone applies nowhere and is left out.
    let mut scopes: BTreeMap<Scope, Vec<&(String, Mapping)>> = BTreeMap::new();
    for entry in rules.maps {
        let Some(scope) = places.scope(&entry.1.device, &entry.1.app) else {
            continue;
        };
        scopes.entry(scope).or_default().push(entry);
    }
    let mut modmaps: BTreeMap<Scope, BTreeMap<String, Output>> = scopes
        .iter()
        .map(|(scope, mappings)| (scope.clone(), scope_entries(mappings, &triggers)))
        .collect();
    // A layer key produces its modifier everywhere; a mapping of that
    // key in a narrower scope refines it there.
    for layer in &layers {
        modmaps
            .entry(Scope::general())
            .or_default()
            .entry(layer.trigger.clone())
            .or_insert(Output::Key(layer.modifier.to_owned()));
    }

    let mut yaml = format!("{MARKER}\n");
    let blocks: Vec<String> = modmaps
        .iter()
        .filter(|(_, entries)| !entries.is_empty())
        .map(|(scope, entries)| modmap_block(scope, entries))
        .collect();
    if blocks.is_empty() {
        yaml.push_str("modmap: []\n");
    } else {
        yaml.push_str("modmap:\n");
        for block in blocks {
            yaml.push_str(&block);
        }
    }

    if !layers.is_empty() {
        yaml.push_str("virtual_modifiers:\n");
        for layer in &layers {
            yaml.push_str(&format!("  - {}\n", layer.modifier));
        }
    }
    let blocks: Vec<String> = layers
        .iter()
        .flat_map(|layer| layer_blocks(layer, rules.maps, &triggers, &places))
        .chain(group_blocks(rules.groups, &places))
        .collect();
    if !blocks.is_empty() {
        yaml.push_str("keymap:\n");
        for block in blocks {
            yaml.push_str(&block);
        }
    }
    yaml
}

/// Result of writing the generated configuration.
#[derive(Debug, PartialEq, Eq)]
pub enum WriteOutcome {
    /// File created or replaced.
    Written(PathBuf),
    /// File already had exactly this content.
    Unchanged(PathBuf),
    /// An existing file without the Keyloom marker was left untouched.
    SkippedForeign(PathBuf),
}

/// The user's configuration directory: `$XDG_CONFIG_HOME`, or
/// `~/.config` when that is unset.
pub(crate) fn config_home() -> Option<PathBuf> {
    std::env::var_os("XDG_CONFIG_HOME")
        .filter(|dir| !dir.is_empty())
        .map(PathBuf::from)
        .filter(|dir| dir.is_absolute())
        .or_else(|| {
            std::env::var_os("HOME")
                .filter(|home| !home.is_empty())
                .map(|home| PathBuf::from(home).join(".config"))
        })
}

/// Where the generated configuration lives:
/// `$XDG_CONFIG_HOME/xremap/keyloom.yml` (usually `~/.config`).
pub fn config_path() -> Option<PathBuf> {
    Some(config_home()?.join("xremap").join("keyloom.yml"))
}

/// Write the generated document to [`config_path`].
///
/// A pre-existing file that Keyloom did not generate is backed up
/// beside the original before being replaced when `overwrite_foreign`
/// is set, and left untouched otherwise.
pub fn write(yaml: &str, overwrite_foreign: bool) -> io::Result<WriteOutcome> {
    let path = config_path().ok_or_else(|| {
        io::Error::new(io::ErrorKind::NotFound, "no home directory to write into")
    })?;
    write_to(&path, yaml, overwrite_foreign)
}

/// [`write`] with an explicit target path.
pub fn write_to(path: &Path, yaml: &str, overwrite_foreign: bool) -> io::Result<WriteOutcome> {
    if let Ok(existing) = fs::read(path) {
        if existing == yaml.as_bytes() {
            return Ok(WriteOutcome::Unchanged(path.to_owned()));
        }
        if !existing.starts_with(MARKER.as_bytes()) {
            if !overwrite_foreign {
                return Ok(WriteOutcome::SkippedForeign(path.to_owned()));
            }
            backup(path)?;
        }
    }
    let dir = path
        .parent()
        .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidInput, "config path has no parent"))?;
    fs::create_dir_all(dir)?;
    // Write-then-rename so a watching xremap never sees a partial file.
    let tmp = path.with_extension("yml.tmp");
    fs::write(&tmp, yaml)?;
    fs::rename(&tmp, path)?;
    Ok(WriteOutcome::Written(path.to_owned()))
}

/// Copy a foreign file to the first free `<name>.bak[.N]` beside it.
pub(crate) fn backup(path: &Path) -> io::Result<()> {
    let file_name = path
        .file_name()
        .map(|name| name.to_string_lossy().into_owned())
        .unwrap_or_default();
    let mut candidate = path.with_file_name(format!("{file_name}.bak"));
    let mut n = 0u32;
    while candidate.exists() {
        n += 1;
        if n > 999 {
            return Err(io::Error::new(
                io::ErrorKind::AlreadyExists,
                "too many xremap config backups",
            ));
        }
        candidate = path.with_file_name(format!("{file_name}.bak.{n}"));
    }
    fs::copy(path, &candidate)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::str::FromStr;

    use super::*;
    use crate::testing::TempDir;
    use crate::ui::model::{AppRef, LayerKey, Rule};

    fn map(
        code: &str,
        tap: Option<&str>,
        hold: Option<&str>,
        device: &str,
        swap: bool,
    ) -> (String, Mapping) {
        (
            code.to_owned(),
            Mapping {
                tap: tap.map(str::to_owned),
                hold: hold.map(str::to_owned),
                device: device.to_owned(),
                swap,
                ..Mapping::default()
            },
        )
    }

    /// A mapping in an application scope.
    fn map_in(app: &str, code: &str, tap: Option<&str>, device: &str) -> (String, Mapping) {
        (
            code.to_owned(),
            Mapping {
                tap: tap.map(str::to_owned),
                device: device.to_owned(),
                app: app.to_owned(),
                ..Mapping::default()
            },
        )
    }

    /// A "normal key here" mapping in an application scope.
    fn normal_in(app: &str, code: &str, device: &str) -> (String, Mapping) {
        (
            code.to_owned(),
            Mapping {
                device: device.to_owned(),
                app: app.to_owned(),
                normal: true,
                ..Mapping::default()
            },
        )
    }

    /// A layer from `(key code, action, device scope)` jobs.
    fn layer(id: &str, trigger: &str, keys: &[(&str, &str, &str)]) -> Layer {
        Layer {
            id: id.to_owned(),
            name: id.to_owned(),
            trigger: trigger.to_owned(),
            keys: keys
                .iter()
                .map(|(code, action, device)| LayerKey {
                    code: (*code).to_owned(),
                    action: (*action).to_owned(),
                    device: (*device).to_owned(),
                    app: String::new(),
                })
                .collect(),
        }
    }

    /// An application scope with the given application ids.
    fn scope(id: &str, name: &str, apps: &[&str]) -> AppScope {
        AppScope {
            id: id.to_owned(),
            name: name.to_owned(),
            apps: apps
                .iter()
                .map(|app| AppRef {
                    id: (*app).to_owned(),
                    name: (*app).to_owned(),
                    aliases: Vec::new(),
                })
                .collect(),
        }
    }

    /// The terminal scope used throughout: id `term`.
    fn terminal() -> AppScope {
        scope("term", "COSMIC Terminal", &["com.system76.CosmicTerm"])
    }

    /// A shortcut rule from `Mods+Key` on both sides.
    fn rule(from: &[&str], from_key: &str, to: &[&str], to_key: &str) -> Rule {
        let chord = |mods: &[&str], key: &str| Chord {
            mods: mods.iter().map(|m| (*m).to_owned()).collect(),
            key: key.to_owned(),
        };
        Rule {
            from: chord(from, from_key),
            to: chord(to, to_key),
            note: String::new(),
        }
    }

    fn group(name: &str, app: &str, any_mod: bool, rules: Vec<Rule>) -> Group {
        Group {
            id: name.to_owned(),
            name: name.to_owned(),
            scope: app.to_owned(),
            enabled: true,
            any_mod,
            rules,
        }
    }

    fn no_devices(id: &str) -> String {
        id.to_owned()
    }

    fn kb1_named(id: &str) -> String {
        if id == "kb1" {
            "Keychron K2 Pro".to_owned()
        } else {
            id.to_owned()
        }
    }

    /// Generate from mappings and layers alone, in every application.
    fn generate(maps: &Maps, layers: &[Layer], device_name: impl Fn(&str) -> String) -> String {
        super::generate(
            Rules {
                maps,
                layers,
                apps: &[],
                groups: &[],
            },
            device_name,
        )
    }

    /// Generate without layers.
    fn without_layers(maps: &Maps) -> String {
        generate(maps, &[], no_devices)
    }

    /// Tap/hold, swap, disabled, device-scoped, and application-scoped
    /// mappings in one document — every mapping construct the
    /// generator can emit.
    fn representative_maps() -> Maps {
        vec![
            map("CapsLock", Some("Escape"), Some("Control"), "all", false),
            map("ControlLeft", Some("Left Alt"), None, "all", true),
            map("MetaLeft", Some("Disabled"), None, "all", false),
            map("F12", Some("Play/Pause"), None, "kb1", false),
            // In the terminal: Caps Lock stays itself, A types B, and
            // on the Keychron alone F12 mutes.
            normal_in("term", "CapsLock", "all"),
            map_in("term", "KeyA", Some("B"), "all"),
            map_in("term", "F12", Some("Mute"), "kb1"),
        ]
    }

    /// A group for every application and one for the terminal, the
    /// latter ignoring held modifiers.
    fn representative_groups() -> Vec<Group> {
        vec![
            group(
                "Desktop",
                "",
                false,
                vec![rule(&["Super"], "C", &["Ctrl"], "C")],
            ),
            group(
                "Terminals",
                "term",
                true,
                vec![rule(&["Super"], "C", &["Ctrl", "Shift"], "C")],
            ),
        ]
    }

    /// Everything [`representative_maps`], [`representative_layers`],
    /// and [`representative_groups`] hold, with the terminal scope.
    fn representative() -> String {
        super::generate(
            Rules {
                maps: &representative_maps(),
                layers: &representative_layers(),
                apps: &[terminal()],
                groups: &representative_groups(),
            },
            kb1_named,
        )
    }

    /// A layer on the tap/hold Caps Lock of [`representative_maps`],
    /// with a remapped, a disabled, and a device-scoped job.
    fn representative_layers() -> Vec<Layer> {
        vec![Layer {
            name: "Navigation".to_owned(),
            ..layer(
                "nav",
                "CapsLock",
                &[
                    ("KeyH", "Arrow Left", "all"),
                    ("KeyY", "Disabled", "all"),
                    ("KeyJ", "Arrow Down", "kb1"),
                ],
            )
        }]
    }

    #[test]
    fn key_symbols_derive_from_evdev() {
        assert_eq!(key_symbol("CapsLock").as_deref(), Some("KEY_CAPSLOCK"));
        assert_eq!(key_symbol("ControlRight").as_deref(), Some("KEY_RIGHTCTRL"));
        assert_eq!(key_symbol("Numpad7").as_deref(), Some("KEY_KP7"));
        assert_eq!(key_symbol("MissionControl").as_deref(), Some("KEY_SCALE"));
        assert_eq!(key_symbol("AudioVolumeUp").as_deref(), Some("KEY_VOLUMEUP"));
        assert_eq!(key_symbol("NoSuchKey"), None);
        assert_eq!(action_symbol("Volume Up").as_deref(), Some("KEY_VOLUMEUP"));
        assert_eq!(action_symbol("Launchpad").as_deref(), Some("KEY_DASHBOARD"));
    }

    /// A key no deck draws is an ordinary source: the Apple keyboards'
    /// Mission Control key can become F3, and a chord can start from a
    /// media key.
    #[test]
    fn off_deck_keys_are_sources_for_mappings_and_chords() {
        let maps = vec![map("MissionControl", Some("F3"), None, "all", false)];
        assert!(without_layers(&maps).contains("      KEY_SCALE: KEY_F3\n"));
        let groups = vec![group(
            "Media",
            "",
            false,
            vec![rule(&["Shift"], "Volume Up", &[], "Volume Up")],
        )];
        let yaml = super::generate(
            Rules {
                maps: &Vec::new(),
                layers: &[],
                apps: &[],
                groups: &groups,
            },
            no_devices,
        );
        assert!(
            yaml.contains("      Shift-KEY_VOLUMEUP: KEY_VOLUMEUP\n"),
            "{yaml}"
        );
    }

    #[test]
    fn every_catalog_action_translates_except_hyper_and_disabled() {
        for (_, actions) in model::ACTION_GROUPS {
            for action in *actions {
                let symbol = action_symbol(action);
                if *action == "Hyper" || *action == "Disabled" {
                    assert_eq!(symbol, None, "{action} has no key");
                } else {
                    assert!(symbol.is_some(), "{action} should translate");
                }
            }
        }
    }

    #[test]
    fn every_deck_key_action_name_translates() {
        for cap in model::registry() {
            let action = model::key_name(cap.code);
            assert!(
                action_symbol(&action).is_some(),
                "captured output {action} should translate"
            );
        }
    }

    /// The output picker must offer every key the app renders, under
    /// exactly the name `key_name` produces (so selection, generation,
    /// and the self-mapping check all agree).
    #[test]
    fn catalog_offers_every_deck_key() {
        for cap in model::registry() {
            let name = model::key_name(cap.code);
            let offered = model::ACTION_GROUPS
                .iter()
                .any(|(_, actions)| actions.iter().any(|action| *action == name));
            assert!(
                offered,
                "{name} ({}) is missing from the action catalog",
                cap.code
            );
        }
    }

    #[test]
    fn simple_remap_is_deterministic() {
        let maps = vec![
            map("AltRight", Some("Right Control"), None, "all", false),
            map("CapsLock", Some("Escape"), None, "all", false),
        ];
        let expected = format!(
            "{MARKER}\n\
             modmap:\n\
             \x20 - name: 'Keyloom mappings'\n\
             \x20   remap:\n\
             \x20     KEY_CAPSLOCK: KEY_ESC\n\
             \x20     KEY_RIGHTALT: KEY_RIGHTCTRL\n"
        );
        assert_eq!(without_layers(&maps), expected);
        // Insertion order does not change the output.
        let reversed: Maps = maps.into_iter().rev().collect();
        assert_eq!(without_layers(&reversed), expected);
    }

    #[test]
    fn tap_hold_emits_held_and_alone() {
        let maps = vec![map(
            "CapsLock",
            Some("Escape"),
            Some("Control"),
            "all",
            false,
        )];
        let yaml = without_layers(&maps);
        assert!(
            yaml.contains(
                "      KEY_CAPSLOCK:\n        held: KEY_LEFTCTRL\n        alone: KEY_ESC\n"
            )
        );
    }

    #[test]
    fn hold_only_keeps_tap_as_the_key_itself() {
        let maps = vec![map("CapsLock", None, Some("Control"), "all", false)];
        let yaml = without_layers(&maps);
        assert!(yaml.contains("        held: KEY_LEFTCTRL\n        alone: KEY_CAPSLOCK\n"));
    }

    #[test]
    fn disabled_key_emits_no_output() {
        let maps = vec![map("MetaLeft", Some("Disabled"), None, "all", false)];
        let yaml = without_layers(&maps);
        assert!(yaml.contains("      KEY_LEFTMETA: []\n"));
    }

    #[test]
    fn swap_generates_both_directions() {
        let maps = vec![map("ControlLeft", Some("Left Alt"), None, "all", true)];
        let yaml = without_layers(&maps);
        assert!(yaml.contains("      KEY_LEFTALT: KEY_LEFTCTRL\n"));
        assert!(yaml.contains("      KEY_LEFTCTRL: KEY_LEFTALT\n"));
    }

    #[test]
    fn explicit_mapping_beats_swap_reverse() {
        let maps = vec![
            map("ControlLeft", Some("Left Alt"), None, "all", true),
            map("AltLeft", Some("Escape"), None, "all", false),
        ];
        let yaml = without_layers(&maps);
        assert!(yaml.contains("      KEY_LEFTALT: KEY_ESC\n"));
        assert!(!yaml.contains("      KEY_LEFTALT: KEY_LEFTCTRL\n"));
    }

    #[test]
    fn untranslatable_hold_falls_back_to_simple_remap() {
        let maps = vec![map("CapsLock", Some("Escape"), Some("Hyper"), "all", false)];
        let yaml = without_layers(&maps);
        assert!(yaml.contains("      KEY_CAPSLOCK: KEY_ESC\n"));
        assert!(!yaml.contains("held"));
    }

    /// xremap applies the first block that mentions a key, so a
    /// keyboard's own block has to come before the one for every
    /// keyboard.
    #[test]
    fn device_scopes_become_filtered_blocks_ahead_of_the_general_one() {
        let maps = vec![
            map("CapsLock", Some("Escape"), None, "all", false),
            map("MetaLeft", Some("Alt"), None, "kb1", false),
        ];
        let yaml = generate(&maps, &[], kb1_named);
        let scoped = yaml
            .find("'Keyloom mappings (Keychron K2 Pro)'")
            .expect("scoped block");
        let unscoped = yaml.find("name: 'Keyloom mappings'\n").expect("all block");
        assert!(scoped < unscoped, "the keyboard's own block comes first");
        assert!(yaml.contains("    device:\n      only: ['Keychron K2 Pro']\n"));
    }

    #[test]
    fn empty_mappings_generate_an_empty_modmap() {
        assert_eq!(
            without_layers(&Vec::new()),
            format!("{MARKER}\nmodmap: []\n")
        );
    }

    /// Golden document covering every generated construct at once; the
    /// same content is validated against a real xremap release by
    /// `generated_documents_parse_with_real_xremap`. Blocks run from
    /// the most specific scope to the general one: the terminal on the
    /// Keychron, the terminal, the Keychron, everywhere.
    #[test]
    fn representative_document_matches_golden_output() {
        let expected = format!(
            "{MARKER}\n\
             modmap:\n\
             \x20 - name: 'Keyloom mappings (COSMIC Terminal, Keychron K2 Pro)'\n\
             \x20   application:\n\
             \x20     only: ['com.system76.CosmicTerm']\n\
             \x20   device:\n\
             \x20     only: ['Keychron K2 Pro']\n\
             \x20   remap:\n\
             \x20     KEY_F12: KEY_MUTE\n\
             \x20 - name: 'Keyloom mappings (COSMIC Terminal)'\n\
             \x20   application:\n\
             \x20     only: ['com.system76.CosmicTerm']\n\
             \x20   remap:\n\
             \x20     KEY_A: KEY_B\n\
             \x20     KEY_CAPSLOCK: KEY_CAPSLOCK\n\
             \x20 - name: 'Keyloom mappings (Keychron K2 Pro)'\n\
             \x20   device:\n\
             \x20     only: ['Keychron K2 Pro']\n\
             \x20   remap:\n\
             \x20     KEY_F12: KEY_PLAYPAUSE\n\
             \x20 - name: 'Keyloom mappings'\n\
             \x20   remap:\n\
             \x20     KEY_CAPSLOCK:\n\
             \x20       held: KEY_BRL_DOT1\n\
             \x20       alone: KEY_ESC\n\
             \x20     KEY_LEFTALT: KEY_LEFTCTRL\n\
             \x20     KEY_LEFTCTRL: KEY_LEFTALT\n\
             \x20     KEY_LEFTMETA: []\n\
             virtual_modifiers:\n\
             \x20 - KEY_BRL_DOT1\n\
             keymap:\n\
             \x20 - name: 'Keyloom layer: Navigation, hold Caps Lock (Keychron K2 Pro)'\n\
             \x20   device:\n\
             \x20     only: ['Keychron K2 Pro']\n\
             \x20   remap:\n\
             \x20     KEY_BRL_DOT1-KEY_J: KEY_DOWN\n\
             \x20 - name: 'Keyloom layer: Navigation, hold Caps Lock'\n\
             \x20   remap:\n\
             \x20     KEY_BRL_DOT1-KEY_H: KEY_LEFT\n\
             \x20     KEY_BRL_DOT1-KEY_Y: []\n\
             \x20 - name: 'Keyloom shortcuts: Terminals (COSMIC Terminal)'\n\
             \x20   application:\n\
             \x20     only: ['com.system76.CosmicTerm']\n\
             \x20   remap:\n\
             \x20     Ctrl-Super-KEY_C: Ctrl-Shift-KEY_C\n\
             \x20     Shift-Super-KEY_C: Ctrl-Shift-KEY_C\n\
             \x20     Alt-Super-KEY_C: Ctrl-Shift-KEY_C\n\
             \x20     Super-KEY_C: Ctrl-Shift-KEY_C\n\
             \x20 - name: 'Keyloom shortcuts: Desktop'\n\
             \x20   remap:\n\
             \x20     Super-KEY_C: Ctrl-KEY_C\n"
        );
        assert_eq!(representative(), expected);
    }

    // --- Application scopes ------------------------------------------

    /// A mapping in an application scope becomes a block filtered on
    /// the scope's application ids (and aliases), ahead of the general
    /// block; "normal here" maps the key to itself there.
    #[test]
    fn application_scopes_become_filtered_blocks_ahead_of_the_general_one() {
        let mut code = scope("code", "VS Code", &["code"]);
        code.apps[0].aliases = vec!["Code".to_owned()];
        let maps = vec![
            map("CapsLock", Some("Escape"), None, "all", false),
            normal_in("code", "CapsLock", "all"),
            map_in("code", "KeyA", Some("B"), "all"),
        ];
        let yaml = super::generate(
            Rules {
                maps: &maps,
                layers: &[],
                apps: &[code],
                groups: &[],
            },
            no_devices,
        );
        let expected = format!(
            "{MARKER}\n\
             modmap:\n\
             \x20 - name: 'Keyloom mappings (VS Code)'\n\
             \x20   application:\n\
             \x20     only: ['code', 'Code']\n\
             \x20   remap:\n\
             \x20     KEY_A: KEY_B\n\
             \x20     KEY_CAPSLOCK: KEY_CAPSLOCK\n\
             \x20 - name: 'Keyloom mappings'\n\
             \x20   remap:\n\
             \x20     KEY_CAPSLOCK: KEY_ESC\n"
        );
        assert_eq!(yaml, expected);
    }

    /// An application's block comes before a keyboard's: an exception
    /// made for an application holds on every keyboard.
    #[test]
    fn an_application_scope_outranks_a_keyboard_scope() {
        let maps = vec![
            map("CapsLock", Some("Escape"), None, "kb1", false),
            normal_in("term", "CapsLock", "all"),
            map_in("term", "CapsLock", Some("Tab"), "kb1"),
        ];
        let yaml = super::generate(
            Rules {
                maps: &maps,
                layers: &[],
                apps: &[terminal()],
                groups: &[],
            },
            kb1_named,
        );
        let both = yaml
            .find("'Keyloom mappings (COSMIC Terminal, Keychron K2 Pro)'")
            .expect("block for the terminal on the keyboard");
        let app = yaml
            .find("'Keyloom mappings (COSMIC Terminal)'")
            .expect("block for the terminal");
        let device = yaml
            .find("'Keyloom mappings (Keychron K2 Pro)'")
            .expect("block for the keyboard");
        assert!(both < app && app < device, "{yaml}");
    }

    /// A mapping whose application scope is gone, or whose scope has no
    /// applications, can apply nowhere and generates nothing.
    #[test]
    fn mappings_in_missing_or_empty_application_scopes_generate_nothing() {
        let maps = vec![
            map_in("gone", "KeyA", Some("B"), "all"),
            map_in("empty", "KeyA", Some("C"), "all"),
        ];
        let yaml = super::generate(
            Rules {
                maps: &maps,
                layers: &[],
                apps: &[scope("empty", "Nothing", &[])],
                groups: &[],
            },
            no_devices,
        );
        assert_eq!(yaml, without_layers(&Vec::new()));
    }

    /// Layer jobs follow a key remapped in one application, the way
    /// they follow one remapped on one keyboard; a key kept normal or
    /// disabled there adds no rule of its own.
    #[test]
    fn layer_rules_refine_per_application() {
        let layers = vec![layer(
            "nav",
            "CapsLock",
            &[("KeyH", "Arrow Left", "all"), ("KeyJ", "Arrow Down", "all")],
        )];
        let maps = vec![
            map("KeyJ", Some("K"), None, "all", false),
            map_in("term", "KeyH", Some("J"), "all"),
            normal_in("term", "KeyJ", "all"),
        ];
        let yaml = super::generate(
            Rules {
                maps: &maps,
                layers: &layers,
                apps: &[terminal()],
                groups: &[],
            },
            no_devices,
        );
        assert!(
            yaml.contains(
                "  - name: 'Keyloom layer: nav, hold Caps Lock (COSMIC Terminal)'\n\
             \x20   application:\n\
             \x20     only: ['com.system76.CosmicTerm']\n\
             \x20   remap:\n\
             \x20     KEY_BRL_DOT1-KEY_J: KEY_LEFT\n\
             \x20 - name: 'Keyloom layer: nav, hold Caps Lock'\n\
             \x20   remap:\n\
             \x20     KEY_BRL_DOT1-KEY_H: KEY_LEFT\n\
             \x20     KEY_BRL_DOT1-KEY_K: KEY_DOWN\n"
            ),
            "{yaml}"
        );
        // J arrives as itself in the terminal, where nothing maps it
        // to Down: the general rule matches K, so the job is lost
        // there, and no rule pretends otherwise.
        assert!(!yaml.contains("KEY_BRL_DOT1-KEY_J: KEY_DOWN"));

        // A key disabled in the terminal never reaches the rules there,
        // so the layer gets no block for the terminal.
        let maps = vec![map_in("term", "KeyH", Some("Disabled"), "all")];
        let yaml = super::generate(
            Rules {
                maps: &maps,
                layers: &layers,
                apps: &[terminal()],
                groups: &[],
            },
            no_devices,
        );
        assert!(yaml.contains("      KEY_H: []\n"), "{yaml}");
        assert!(
            !yaml.contains("Keyloom layer: nav, hold Caps Lock (COSMIC Terminal)"),
            "{yaml}"
        );
    }

    /// A layer key kept normal in an application maps to itself there,
    /// ahead of the entry that holds the layer everywhere: the layer
    /// never activates in that application.
    #[test]
    fn a_normal_key_keeps_its_layer_off_in_that_application() {
        let layers = vec![layer("nav", "CapsLock", &[("KeyH", "Arrow Left", "all")])];
        let maps = vec![normal_in("term", "CapsLock", "all")];
        let yaml = super::generate(
            Rules {
                maps: &maps,
                layers: &layers,
                apps: &[terminal()],
                groups: &[],
            },
            no_devices,
        );
        let normal = yaml
            .find("      KEY_CAPSLOCK: KEY_CAPSLOCK\n")
            .expect("the key stays itself in the terminal");
        let held = yaml
            .find("      KEY_CAPSLOCK: KEY_BRL_DOT1\n")
            .expect("the key holds the layer elsewhere");
        assert!(normal < held);
    }

    // --- Shortcut groups ---------------------------------------------

    /// A sided modifier becomes the key itself, which xremap matches
    /// alone, while a side-less one stays the alias for either key;
    /// "any modifier" treats a sided modifier as its family held.
    #[test]
    fn sided_modifiers_generate_the_key_and_side_less_ones_the_alias() {
        let groups = vec![
            group(
                "Terminals",
                "",
                false,
                vec![rule(&["Right Ctrl"], "C", &["Ctrl", "Shift"], "C")],
            ),
            group(
                "Sided any",
                "",
                true,
                vec![rule(&["Left Alt"], "Backspace", &["Ctrl"], "Backspace")],
            ),
        ];
        let yaml = super::generate(
            Rules {
                maps: &Vec::new(),
                layers: &[],
                apps: &[],
                groups: &groups,
            },
            no_devices,
        );
        assert!(
            yaml.contains("      KEY_RIGHTCTRL-KEY_C: Ctrl-Shift-KEY_C\n"),
            "{yaml}"
        );
        assert!(
            yaml.contains(
                "    remap:\n\
                 \x20     Ctrl-KEY_LEFTALT-KEY_BACKSPACE: Ctrl-KEY_BACKSPACE\n\
                 \x20     Shift-KEY_LEFTALT-KEY_BACKSPACE: Ctrl-KEY_BACKSPACE\n\
                 \x20     Super-KEY_LEFTALT-KEY_BACKSPACE: Ctrl-KEY_BACKSPACE\n\
                 \x20     KEY_LEFTALT-KEY_BACKSPACE: Ctrl-KEY_BACKSPACE\n"
            ),
            "{yaml}"
        );
    }

    /// A rule from a key to itself adds nothing on its own; with "any
    /// modifier" it adds only the entries that drop a held modifier, so
    /// the plain key keeps passing through.
    #[test]
    fn identity_rules_generate_only_their_any_modifier_entries() {
        let groups = vec![
            group(
                "Plain",
                "",
                false,
                vec![rule(&[], "Volume Up", &[], "Volume Up")],
            ),
            group(
                "Media keys ignore modifiers",
                "",
                true,
                vec![rule(&[], "Volume Up", &[], "Volume Up")],
            ),
        ];
        let yaml = super::generate(
            Rules {
                maps: &Vec::new(),
                layers: &[],
                apps: &[],
                groups: &groups,
            },
            no_devices,
        );
        let expected = format!(
            "{MARKER}\n\
             modmap: []\n\
             keymap:\n\
             \x20 - name: 'Keyloom shortcuts: Media keys ignore modifiers'\n\
             \x20   remap:\n\
             \x20     Ctrl-KEY_VOLUMEUP: KEY_VOLUMEUP\n\
             \x20     Shift-KEY_VOLUMEUP: KEY_VOLUMEUP\n\
             \x20     Alt-KEY_VOLUMEUP: KEY_VOLUMEUP\n\
             \x20     Super-KEY_VOLUMEUP: KEY_VOLUMEUP\n"
        );
        assert_eq!(yaml, expected);
    }

    /// Paused groups, incomplete rules, and keys xremap cannot name
    /// generate nothing; a chord repeated in a group is written once.
    #[test]
    fn shortcut_groups_skip_what_cannot_apply() {
        let mut paused = group("Paused", "", false, vec![rule(&["Ctrl"], "A", &[], "B")]);
        paused.enabled = false;
        let groups = vec![
            paused,
            group(
                "Odd",
                "",
                false,
                vec![
                    rule(&["Ctrl"], "", &[], "B"),
                    rule(&["Ctrl"], "A", &[], ""),
                    rule(&["Ctrl"], "Hyper", &[], "B"),
                    rule(&["Ctrl"], "A", &["Any"], "Hyper"),
                    rule(&["Ctrl"], "A", &["Any"], "B"),
                    rule(&["Ctrl"], "A", &[], "C"),
                ],
            ),
            group("Gone", "gone", false, vec![rule(&["Ctrl"], "A", &[], "B")]),
        ];
        let yaml = super::generate(
            Rules {
                maps: &Vec::new(),
                layers: &[],
                apps: &[],
                groups: &groups,
            },
            no_devices,
        );
        let expected = format!(
            "{MARKER}\n\
             modmap: []\n\
             keymap:\n\
             \x20 - name: 'Keyloom shortcuts: Odd'\n\
             \x20   remap:\n\
             \x20     Ctrl-KEY_A: KEY_B\n"
        );
        assert_eq!(yaml, expected);
    }

    // --- Layers ---------------------------------------------------------

    /// The stand-ins must be names xremap's evdev accepts, and none of
    /// them may be a key on the deck, or that key would activate the
    /// layer too.
    #[test]
    fn layer_modifiers_are_known_keys_off_the_deck() {
        for name in LAYER_MODIFIERS {
            let key = KeyCode::from_str(name).unwrap_or_else(|_| panic!("{name} is a key"));
            assert_eq!(evdev_name(key.0).as_deref(), Some(name));
            assert!(model::key_by_evdev(key.0).is_none(), "{name} is a deck key");
        }
        assert_eq!(MAX_LAYERS, LAYER_MODIFIERS.len());
    }

    #[test]
    fn modifier_keys_are_recognized() {
        for code in ["ShiftLeft", "ControlRight", "AltRight", "MetaLeft"] {
            assert!(is_modifier_key(code), "{code}");
        }
        for code in ["CapsLock", "Space", "Fn", "KeyA", "NoSuchKey"] {
            assert!(!is_modifier_key(code), "{code}");
        }
    }

    /// The simplest layer: the key becomes the layer's modifier and the
    /// jobs become rules on it. Tapping the key then does nothing.
    #[test]
    fn a_layer_key_becomes_a_virtual_modifier_with_rules() {
        let layers = vec![layer("nav", "CapsLock", &[("KeyH", "Arrow Left", "all")])];
        let yaml = generate(&Vec::new(), &layers, no_devices);
        let expected = format!(
            "{MARKER}\n\
             modmap:\n\
             \x20 - name: 'Keyloom mappings'\n\
             \x20   remap:\n\
             \x20     KEY_CAPSLOCK: KEY_BRL_DOT1\n\
             virtual_modifiers:\n\
             \x20 - KEY_BRL_DOT1\n\
             keymap:\n\
             \x20 - name: 'Keyloom layer: nav, hold Caps Lock'\n\
             \x20   remap:\n\
             \x20     KEY_BRL_DOT1-KEY_H: KEY_LEFT\n"
        );
        assert_eq!(yaml, expected);
    }

    /// A tap action on the layer key survives as the tap side of a
    /// tap/hold key whose hold side is the layer.
    #[test]
    fn a_layer_key_keeps_its_tap_action() {
        let maps = vec![map("CapsLock", Some("Escape"), None, "all", false)];
        let layers = vec![layer("nav", "CapsLock", &[("KeyH", "Arrow Left", "all")])];
        let yaml = generate(&maps, &layers, no_devices);
        assert!(
            yaml.contains(
                "      KEY_CAPSLOCK:\n        held: KEY_BRL_DOT1\n        alone: KEY_ESC\n"
            )
        );
        assert!(yaml.contains("      KEY_BRL_DOT1-KEY_H: KEY_LEFT\n"));
    }

    /// Holding the key now activates the layer; a hold action it had
    /// is superseded. A disabled or untranslatable tap adds nothing.
    #[test]
    fn a_layer_supersedes_the_layer_keys_hold_action() {
        let layers = vec![layer("nav", "CapsLock", &[("KeyH", "Arrow Left", "all")])];
        let maps = vec![map(
            "CapsLock",
            Some("Escape"),
            Some("Left Control"),
            "all",
            false,
        )];
        let yaml = generate(&maps, &layers, no_devices);
        assert!(yaml.contains("        held: KEY_BRL_DOT1\n        alone: KEY_ESC\n"));
        assert!(!yaml.contains("KEY_LEFTCTRL"));

        for tap in ["Disabled", "Hyper"] {
            let maps = vec![map(
                "CapsLock",
                Some(tap),
                Some("Left Control"),
                "all",
                false,
            )];
            let yaml = generate(&maps, &layers, no_devices);
            assert!(
                yaml.contains("      KEY_CAPSLOCK: KEY_BRL_DOT1\n"),
                "{tap}: {yaml}"
            );
            assert!(!yaml.contains("held"), "{tap}");
        }
    }

    /// Mappings apply before rules, so a job on a remapped key has to
    /// match what the key became. A key whose tap is disabled never
    /// reaches the rules; a hold-only key still arrives as itself.
    #[test]
    fn layer_rules_match_the_remapped_key() {
        let layers = vec![layer("nav", "CapsLock", &[("KeyH", "Arrow Left", "all")])];

        let maps = vec![map("KeyH", Some("J"), None, "all", false)];
        let yaml = generate(&maps, &layers, no_devices);
        assert!(yaml.contains("      KEY_BRL_DOT1-KEY_J: KEY_LEFT\n"));
        assert!(!yaml.contains("-KEY_H:"));

        let maps = vec![map("KeyH", Some("J"), Some("Left Control"), "all", false)];
        let yaml = generate(&maps, &layers, no_devices);
        assert!(yaml.contains("      KEY_BRL_DOT1-KEY_J: KEY_LEFT\n"));

        let maps = vec![map("KeyH", None, Some("Left Control"), "all", false)];
        let yaml = generate(&maps, &layers, no_devices);
        assert!(yaml.contains("      KEY_BRL_DOT1-KEY_H: KEY_LEFT\n"));

        let maps = vec![map("KeyH", Some("Disabled"), None, "all", false)];
        let yaml = generate(&maps, &layers, no_devices);
        assert!(!yaml.contains("keymap"), "{yaml}");
        assert!(
            yaml.contains("virtual_modifiers"),
            "the layer key still holds"
        );
    }

    /// A mapping scoped to one keyboard refines the job there while the
    /// general rule keeps matching the unmapped key elsewhere; a job
    /// scoped to another keyboard ignores it.
    #[test]
    fn scoped_mappings_refine_layer_rules_per_keyboard() {
        let maps = vec![map("KeyH", Some("J"), None, "kb1", false)];
        let layers = vec![layer("nav", "CapsLock", &[("KeyH", "Arrow Left", "all")])];
        let yaml = generate(&maps, &layers, kb1_named);
        assert!(yaml.contains(
            "  - name: 'Keyloom layer: nav, hold Caps Lock (Keychron K2 Pro)'\n\
             \x20   device:\n\
             \x20     only: ['Keychron K2 Pro']\n\
             \x20   remap:\n\
             \x20     KEY_BRL_DOT1-KEY_J: KEY_LEFT\n"
        ));
        assert!(yaml.contains(
            "  - name: 'Keyloom layer: nav, hold Caps Lock'\n\
             \x20   remap:\n\
             \x20     KEY_BRL_DOT1-KEY_H: KEY_LEFT\n"
        ));

        let layers = vec![layer("nav", "CapsLock", &[("KeyH", "Arrow Left", "kb2")])];
        let yaml = generate(&maps, &layers, kb1_named);
        assert!(yaml.contains("      KEY_BRL_DOT1-KEY_H: KEY_LEFT\n"));
        assert!(!yaml.contains("KEY_BRL_DOT1-KEY_J"));
    }

    /// A layer key's own mapping scoped to one keyboard keeps its tap
    /// action there, ahead of the entry that holds the layer everywhere.
    #[test]
    fn a_scoped_mapping_of_the_layer_key_refines_its_entry() {
        let maps = vec![map("CapsLock", Some("Escape"), None, "kb1", false)];
        let layers = vec![layer("nav", "CapsLock", &[("KeyH", "Arrow Left", "all")])];
        let yaml = generate(&maps, &layers, kb1_named);
        let scoped = yaml
            .find("      KEY_CAPSLOCK:\n        held: KEY_BRL_DOT1\n        alone: KEY_ESC\n")
            .expect("tap/hold entry for the keyboard");
        let general = yaml
            .find("      KEY_CAPSLOCK: KEY_BRL_DOT1\n")
            .expect("plain entry for every keyboard");
        assert!(scoped < general);
    }

    /// Physical modifiers always pass through xremap, and a key that
    /// holds a layer is remapped before rules apply: neither can take a
    /// job. A disabled job emits nothing.
    #[test]
    fn modifiers_and_layer_keys_take_no_jobs_and_disabled_jobs_emit_nothing() {
        let layers = vec![
            layer(
                "nav",
                "CapsLock",
                &[
                    ("ShiftLeft", "Home", "all"),
                    ("CapsLock", "Escape", "all"),
                    ("Space", "Enter", "all"),
                    ("KeyY", "Disabled", "all"),
                    ("KeyH", "Hyper", "all"),
                ],
            ),
            layer("num", "Space", &[("KeyJ", "1", "all")]),
        ];
        let yaml = generate(&Vec::new(), &layers, no_devices);
        assert!(!yaml.contains("KEY_LEFTSHIFT"));
        assert!(!yaml.contains("KEY_BRL_DOT1-KEY_CAPSLOCK"));
        assert!(!yaml.contains("KEY_BRL_DOT1-KEY_SPACE"));
        assert!(!yaml.contains("KEY_BRL_DOT1-KEY_H"));
        assert!(yaml.contains("      KEY_BRL_DOT1-KEY_Y: []\n"));
        assert!(yaml.contains("      KEY_SPACE: KEY_BRL_DOT2\n"));
        assert!(yaml.contains("      KEY_BRL_DOT2-KEY_J: KEY_1\n"));
        assert!(yaml.contains("virtual_modifiers:\n  - KEY_BRL_DOT1\n  - KEY_BRL_DOT2\n"));
    }

    /// Each layer takes the next modifier in profile order; layers past
    /// the pool, and layers without a known key, generate nothing.
    #[test]
    fn layers_take_modifiers_in_order_within_the_pool() {
        let triggers = [
            "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11",
        ];
        let mut layers: Vec<Layer> = triggers
            .iter()
            .map(|trigger| layer(trigger, trigger, &[("KeyH", "Arrow Left", "all")]))
            .collect();
        layers.insert(0, layer("unset", "", &[("KeyH", "Arrow Left", "all")]));
        layers.insert(
            0,
            layer("unknown", "NoSuchKey", &[("KeyH", "Arrow Left", "all")]),
        );
        let yaml = generate(&Vec::new(), &layers, no_devices);
        assert!(yaml.contains("      KEY_F1: KEY_BRL_DOT1\n"));
        assert!(yaml.contains("      KEY_F10: KEY_BRL_DOT10\n"));
        assert!(!yaml.contains("KEY_F11"), "{yaml}");
        assert!(yaml.contains("      KEY_BRL_DOT10-KEY_H: KEY_LEFT\n"));
        assert_eq!(yaml.matches("  - KEY_BRL_DOT").count(), MAX_LAYERS);

        let none = vec![layer("unset", "", &[("KeyH", "Arrow Left", "all")])];
        assert_eq!(
            generate(&Vec::new(), &none, no_devices),
            without_layers(&Vec::new())
        );
    }

    /// Write the layer and application documents that
    /// `scripts/verify-layers-with-xremap.sh` runs through xremap's own
    /// event-handler tests into `$KEYLOOM_HARNESS_DIR`; the expectations
    /// live beside the script.
    #[test]
    #[ignore = "writes files for the xremap harness script"]
    fn dump_documents_for_the_xremap_harness() {
        let dir = PathBuf::from(
            std::env::var("KEYLOOM_HARNESS_DIR")
                .expect("KEYLOOM_HARNESS_DIR names the output directory"),
        );
        let navigation = model::starter_profiles()
            .into_iter()
            .find(|starter| starter.profile.id == "navigation")
            .expect("navigation starter");
        // Caps Lock holds a layer with no tap action; Space taps a
        // space and holds a second layer.
        let two_layers = vec![
            Layer {
                name: "Navigation".to_owned(),
                ..layer(
                    "nav",
                    "CapsLock",
                    &[("KeyH", "Arrow Left", "all"), ("KeyY", "Disabled", "all")],
                )
            },
            Layer {
                name: "Numbers".to_owned(),
                ..layer(
                    "num",
                    "Space",
                    &[("KeyJ", "1", "all"), ("KeyH", "2", "all")],
                )
            },
        ];
        let space_taps = vec![map("Space", Some("Space"), None, "all", false)];
        // A job on a key whose normal press is remapped (H types J).
        let h_types_j = vec![map("KeyH", Some("J"), None, "all", false)];
        let nav_only = vec![layer("nav", "CapsLock", &[("KeyH", "Arrow Left", "all")])];
        // Caps Lock taps Escape and holds a navigation layer everywhere
        // except the terminal, where it stays Caps Lock; A types B only
        // in the terminal; Super+C copies the terminal's way there and
        // the usual way elsewhere.
        let app_scoped = super::generate(
            Rules {
                maps: &vec![
                    map("CapsLock", Some("Escape"), None, "all", false),
                    normal_in("term", "CapsLock", "all"),
                    map_in("term", "KeyA", Some("B"), "all"),
                ],
                layers: &nav_only,
                apps: &[terminal()],
                groups: &[
                    group(
                        "Desktop",
                        "",
                        false,
                        vec![rule(&["Super"], "C", &["Ctrl"], "C")],
                    ),
                    group(
                        "Terminals",
                        "term",
                        false,
                        vec![rule(&["Super"], "C", &["Ctrl", "Shift"], "C")],
                    ),
                ],
            },
            no_devices,
        );
        // A shortcut keyed to the right Ctrl alone, as a Mac-style setup
        // does when the Command keys become Right Ctrl.
        let sided = super::generate(
            Rules {
                maps: &Vec::new(),
                layers: &[],
                apps: &[],
                groups: &[group(
                    "Terminals",
                    "",
                    false,
                    vec![rule(&["Right Ctrl"], "C", &["Ctrl", "Shift"], "C")],
                )],
            },
            no_devices,
        );
        // Volume Up works while a modifier is held, and alone passes
        // through untouched.
        let media = super::generate(
            Rules {
                maps: &Vec::new(),
                layers: &[],
                apps: &[],
                groups: &[group(
                    "Media keys ignore modifiers",
                    "",
                    true,
                    vec![rule(&[], "Volume Up", &[], "Volume Up")],
                )],
            },
            no_devices,
        );
        for (name, yaml) in [
            (
                "navigation.yml",
                generate(&navigation.maps, &navigation.layers, no_devices),
            ),
            (
                "two-layers.yml",
                generate(&space_taps, &two_layers, no_devices),
            ),
            (
                "remapped-key.yml",
                generate(&h_types_j, &nav_only, no_devices),
            ),
            ("app-scoped.yml", app_scoped),
            ("sided-modifiers.yml", sided),
            ("media-any-modifier.yml", media),
        ] {
            fs::write(dir.join(name), yaml).expect("harness directory is writable");
        }
    }

    #[test]
    fn config_path_uses_keyloom_filename_in_xremap_directory() {
        let path = config_path().expect("test environment has a config or home directory");
        assert!(path.ends_with("xremap/keyloom.yml"));
    }

    #[test]
    fn write_respects_foreign_files_and_backs_them_up() {
        let temp = TempDir::new("write");
        let dir = temp.path();
        let path = dir.join("keyloom.yml");
        let ours = without_layers(&Vec::new());

        // Fresh write, then an identical write is a no-op.
        assert_eq!(
            write_to(&path, &ours, false).unwrap(),
            WriteOutcome::Written(path.clone())
        );
        assert_eq!(
            write_to(&path, &ours, false).unwrap(),
            WriteOutcome::Unchanged(path.clone())
        );

        // A hand-written file is preserved unless overwriting is allowed.
        fs::write(&path, "modmap: [] # hand written\n").unwrap();
        let updated = format!("{ours}# updated\n");
        assert_eq!(
            write_to(&path, &updated, false).unwrap(),
            WriteOutcome::SkippedForeign(path.clone())
        );
        assert_eq!(
            write_to(&path, &updated, true).unwrap(),
            WriteOutcome::Written(path.clone())
        );
        assert_eq!(fs::read_to_string(&path).unwrap(), updated);
        assert_eq!(
            fs::read_to_string(dir.join("keyloom.yml.bak")).unwrap(),
            "modmap: [] # hand written\n"
        );

        // Our own older output is replaced without a backup.
        assert_eq!(
            write_to(&path, &ours, false).unwrap(),
            WriteOutcome::Written(path.clone())
        );
        assert!(!dir.join("keyloom.yml.bak.1").exists());
    }

    /// End-to-end oracle against a real xremap binary: the pinned CLI
    /// loads its configuration *before* selecting devices, so pointing
    /// it at a device name that cannot exist distinguishes "config
    /// parsed" (fails preparing input devices) from "config rejected"
    /// (fails loading the config).
    ///
    /// Ignored during normal local tests to avoid launching the installed
    /// xremap. CI installs the pinned release and explicitly runs this test
    /// with `--ignored`; a missing binary is a failure.
    #[test]
    #[ignore = "launches xremap; CI runs this explicitly with a pinned binary"]
    fn generated_documents_parse_with_real_xremap() {
        use std::process::Command;

        // Every known physical key as a remap source.
        let sources: Vec<&str> = model::registry().map(|cap| cap.code).collect();
        let all_sources: Maps = sources
            .iter()
            .map(|code| map(code, Some("Escape"), None, "all", false))
            .collect();
        // Every translatable catalog action as an output (plus
        // Disabled; Hyper has no key and is dropped by the generator).
        // The catalog holds more actions than there are keys, so cycle
        // sources; one source keeps only its last action, which is fine
        // because every action still appears in some document chunk
        // below.
        let actions: Vec<&&str> = model::ACTION_GROUPS
            .iter()
            .flat_map(|(_, actions)| actions.iter())
            .collect();
        let all_action_chunks: Vec<Maps> = actions
            .chunks(sources.len())
            .map(|chunk| {
                chunk
                    .iter()
                    .enumerate()
                    .map(|(i, action)| map(sources[i], Some(action), None, "all", false))
                    .collect()
            })
            .collect();

        // Every layer modifier in use at once, with every non-modifier
        // key as a job in one layer and every action as a job's output
        // across the others.
        let triggers = ["F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10"];
        let job_keys: Vec<&str> = sources
            .iter()
            .copied()
            .filter(|code| !triggers.contains(code) && !is_modifier_key(code))
            .collect();
        let mut all_layers = vec![layer(
            "all-keys",
            triggers[0],
            &job_keys
                .iter()
                .map(|code| (*code, "Escape", "all"))
                .collect::<Vec<_>>(),
        )];
        for (i, chunk) in actions.chunks(job_keys.len()).enumerate() {
            let jobs: Vec<(&str, &str, &str)> = chunk
                .iter()
                .enumerate()
                .map(|(k, action)| (job_keys[k], **action, "all"))
                .collect();
            all_layers.push(layer(&format!("actions-{i}"), triggers[i + 1], &jobs));
        }
        for trigger in &triggers[all_layers.len()..] {
            all_layers.push(layer(trigger, trigger, &[("KeyH", "Arrow Left", "all")]));
        }
        assert_eq!(all_layers.len(), MAX_LAYERS);

        let mut documents = vec![
            ("empty".to_owned(), without_layers(&Vec::new())),
            ("representative".to_owned(), representative()),
            ("all-sources".to_owned(), without_layers(&all_sources)),
            (
                "all-layers".to_owned(),
                generate(&Vec::new(), &all_layers, no_devices),
            ),
        ];
        for (i, chunk) in all_action_chunks.iter().enumerate() {
            documents.push((format!("all-actions-{i}"), without_layers(chunk)));
        }

        let temp = TempDir::new("validate");
        let dir = temp.path();
        for (name, yaml) in &documents {
            let path = dir.join(format!("{name}.yml"));
            fs::write(&path, yaml).unwrap();
            let output = Command::new("xremap")
                .arg("--device")
                .arg("keyloom-validation-no-such-device")
                .arg(&path)
                .output()
                .expect("xremap validation requires the pinned binary on PATH");
            let stderr = String::from_utf8_lossy(&output.stderr);
            assert!(
                !stderr.contains("Failed to load config"),
                "{name}: xremap rejected the generated config:\n{stderr}\n---\n{yaml}"
            );
            assert!(
                stderr.contains("Failed to prepare input devices"),
                "{name}: xremap did not reach device selection:\n{stderr}"
            );
        }
    }
}
