//! Translation layer from Keyloom's internal mapping model to a valid
//! xremap configuration file.
//!
//! The rule model in [`crate::ui::model`] is the source of truth; the
//! YAML written to the user's config directory is generated output.
//! Generation is deterministic: identical mappings always produce
//! byte-identical YAML, with sources sorted by their xremap key name.

use std::collections::BTreeMap;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use evdev::KeyCode;

use crate::ui::model::{self, Mapping, Maps};

/// First line of every file Keyloom generates. Files that don't start
/// with this marker are treated as foreign and never silently replaced.
const MARKER: &str = "# Generated by Keyloom. Do not edit by hand; Keyloom overwrites this file.";

/// xremap key name (`KEY_*`) for a physical key on the deck, derived
/// from its evdev scancode.
pub fn key_symbol(code: &str) -> Option<String> {
    model::key(code).and_then(|cap| evdev_name(cap.evdev))
}

/// xremap key name (`KEY_*`) for an action from the editor's catalog
/// (e.g. `Escape`, `Right Control`, `Play/Pause`).
///
/// Returns `None` for actions with no evdev key, such as `Hyper` and
/// `Disabled` (the generator handles `Disabled` itself).
pub fn action_symbol(action: &str) -> Option<String> {
    // Actions named after a physical key ("Caps Lock", "Right Control",
    // "Numpad 7", "ISO Backslash", …) resolve through its scancode.
    if let Some(cap) = model::registry().find(|cap| model::key_name(cap.code) == action) {
        return evdev_name(cap.evdev);
    }
    // Catalog names that differ from the deck's key names, plus keys
    // that have no cap on the rendered keyboard (media, brightness).
    const ACTIONS: &[(&str, &str)] = &[
        ("Control", "KEY_LEFTCTRL"),
        ("Shift", "KEY_LEFTSHIFT"),
        ("Alt", "KEY_LEFTALT"),
        ("Super", "KEY_LEFTMETA"),
        ("Left", "KEY_LEFT"),
        ("Right", "KEY_RIGHT"),
        ("Up", "KEY_UP"),
        ("Down", "KEY_DOWN"),
        ("Bracket Left", "KEY_LEFTBRACE"),
        ("Bracket Right", "KEY_RIGHTBRACE"),
        ("Play/Pause", "KEY_PLAYPAUSE"),
        ("Next", "KEY_NEXTSONG"),
        ("Previous", "KEY_PREVIOUSSONG"),
        ("Mute", "KEY_MUTE"),
        ("Volume Up", "KEY_VOLUMEUP"),
        ("Volume Down", "KEY_VOLUMEDOWN"),
        ("Brightness Up", "KEY_BRIGHTNESSUP"),
        ("Brightness Down", "KEY_BRIGHTNESSDOWN"),
    ];
    ACTIONS
        .iter()
        .find(|(name, _)| *name == action)
        .map(|(_, symbol)| (*symbol).to_owned())
}

/// Canonical evdev name for a scancode (`KEY_CAPSLOCK`), which xremap
/// accepts directly. `None` for codes evdev has no name for.
fn evdev_name(scancode: u16) -> Option<String> {
    let name = format!("{:?}", KeyCode(scancode));
    name.starts_with("KEY_").then_some(name)
}

/// What a source key produces in the generated modmap.
#[derive(Clone, Debug, PartialEq, Eq)]
enum Output {
    /// Simple remap to one key.
    Key(String),
    /// Key emits nothing (`Disabled` in the editor).
    Disabled,
    /// Tap/hold multi-purpose key. `None` slots emit nothing.
    TapHold {
        alone: Option<String>,
        held: Option<String>,
    },
}

/// Resolve one mapping into `(source symbol, output)`, or `None` when
/// nothing about it can be expressed as an xremap rule.
fn resolve(code: &str, mapping: &Mapping) -> Option<(String, Output)> {
    let source = key_symbol(code)?;
    // `Some(None)` disables the slot, `Some(Some(_))` remaps it, and
    // `None` means the slot is unset or holds an untranslatable action
    // (e.g. `Hyper`); such a slot is dropped rather than dropping the
    // whole mapping.
    let slot = |action: &Option<String>| -> Option<Option<String>> {
        match action.as_deref() {
            Some("Disabled") => Some(None),
            Some(action) => action_symbol(action).map(Some),
            None => None,
        }
    };
    let tap = slot(&mapping.tap);
    let output = match slot(&mapping.hold) {
        Some(held) => Output::TapHold {
            // Tapping falls back to the key's own behavior when only a
            // hold action is configured (xremap requires `alone`).
            alone: tap.unwrap_or(Some(source.clone())),
            held,
        },
        None => match tap {
            Some(None) => Output::Disabled,
            Some(Some(key)) => Output::Key(key),
            None => return None,
        },
    };
    Some((source, output))
}

/// Entries for one device scope, sorted by source symbol.
fn scope_entries(mappings: &[&(String, Mapping)]) -> BTreeMap<String, Output> {
    let mut entries = BTreeMap::new();
    // Explicit mappings first; the model keeps one mapping per key.
    for (code, mapping) in mappings {
        if let Some((source, output)) = resolve(code, mapping) {
            entries.entry(source).or_insert(output);
        }
    }
    // Two-way swaps add the reverse entry unless the reverse source
    // already has an explicit mapping.
    for (code, mapping) in mappings {
        if !mapping.swap || mapping.hold.is_some() {
            continue;
        }
        let (Some(source), Some(tap)) = (key_symbol(code), mapping.tap.as_deref()) else {
            continue;
        };
        if let Some(reverse) = action_symbol(tap)
            && reverse != source
        {
            entries.entry(reverse).or_insert(Output::Key(source));
        }
    }
    entries
}

/// Single-quote a YAML scalar (device names may contain anything).
fn quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

/// Mappings grouped by device scope; `None` is the unscoped (`all`)
/// group, `Some((resolved name, id))` a specific keyboard.
type Scopes<'a> = BTreeMap<Option<(String, String)>, Vec<&'a (String, Mapping)>>;

/// Render the active profile's mappings as a complete xremap document.
///
/// `device_name` resolves a device scope id to the display name xremap
/// should match on. Mappings scoped to `all` form the first block;
/// device-scoped blocks follow, sorted by resolved name.
pub fn generate(maps: &Maps, device_name: impl Fn(&str) -> String) -> String {
    // Group mappings by device scope, "all"/empty first.
    let mut scopes: Scopes = BTreeMap::new();
    for entry in maps {
        let scope = match entry.1.device.as_str() {
            "" | "all" => None,
            id => Some((device_name(id), id.to_owned())),
        };
        scopes.entry(scope).or_default().push(entry);
    }

    let mut blocks = Vec::new();
    for (scope, mappings) in &scopes {
        let entries = scope_entries(mappings);
        if entries.is_empty() {
            continue;
        }
        let mut block = String::new();
        match scope {
            None => block.push_str("  - name: Keyloom mappings\n"),
            Some((name, _)) => {
                block.push_str(&format!(
                    "  - name: {}\n",
                    quote(&format!("Keyloom mappings ({name})"))
                ));
                block.push_str("    device:\n");
                block.push_str(&format!("      only: [{}]\n", quote(name)));
            }
        }
        block.push_str("    remap:\n");
        for (source, output) in &entries {
            match output {
                Output::Key(key) => block.push_str(&format!("      {source}: {key}\n")),
                Output::Disabled => block.push_str(&format!("      {source}: []\n")),
                Output::TapHold { alone, held } => {
                    let slot =
                        |slot: &Option<String>| slot.clone().unwrap_or_else(|| "[]".to_owned());
                    block.push_str(&format!("      {source}:\n"));
                    block.push_str(&format!("        held: {}\n", slot(held)));
                    block.push_str(&format!("        alone: {}\n", slot(alone)));
                }
            }
        }
        blocks.push(block);
    }

    let mut yaml = format!("{MARKER}\n");
    if blocks.is_empty() {
        yaml.push_str("modmap: []\n");
    } else {
        yaml.push_str("modmap:\n");
        for block in blocks {
            yaml.push_str(&block);
        }
    }
    yaml
}

/// Result of writing the generated configuration.
#[derive(Debug, PartialEq, Eq)]
pub enum WriteOutcome {
    /// File created or replaced.
    Written(PathBuf),
    /// File already had exactly this content.
    Unchanged(PathBuf),
    /// An existing file without the Keyloom marker was left untouched.
    SkippedForeign(PathBuf),
}

/// Where the generated configuration lives:
/// `$XDG_CONFIG_HOME/xremap/config.yml` (usually `~/.config`).
pub fn config_path() -> Option<PathBuf> {
    let base = std::env::var_os("XDG_CONFIG_HOME")
        .filter(|dir| !dir.is_empty())
        .map(PathBuf::from)
        .filter(|dir| dir.is_absolute())
        .or_else(|| {
            std::env::var_os("HOME")
                .filter(|home| !home.is_empty())
                .map(|home| PathBuf::from(home).join(".config"))
        })?;
    Some(base.join("xremap").join("config.yml"))
}

/// Write the generated document to [`config_path`].
///
/// A pre-existing file that Keyloom did not generate is backed up
/// beside the original before being replaced when `overwrite_foreign`
/// is set, and left untouched otherwise.
pub fn write(yaml: &str, overwrite_foreign: bool) -> io::Result<WriteOutcome> {
    let path = config_path().ok_or_else(|| {
        io::Error::new(io::ErrorKind::NotFound, "no home directory to write into")
    })?;
    write_to(&path, yaml, overwrite_foreign)
}

/// [`write`] with an explicit target path.
pub fn write_to(path: &Path, yaml: &str, overwrite_foreign: bool) -> io::Result<WriteOutcome> {
    if let Ok(existing) = fs::read(path) {
        if existing == yaml.as_bytes() {
            return Ok(WriteOutcome::Unchanged(path.to_owned()));
        }
        if !existing.starts_with(MARKER.as_bytes()) {
            if !overwrite_foreign {
                return Ok(WriteOutcome::SkippedForeign(path.to_owned()));
            }
            backup(path)?;
        }
    }
    let dir = path
        .parent()
        .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidInput, "config path has no parent"))?;
    fs::create_dir_all(dir)?;
    // Write-then-rename so a watching xremap never sees a partial file.
    let tmp = path.with_extension("yml.tmp");
    fs::write(&tmp, yaml)?;
    fs::rename(&tmp, path)?;
    Ok(WriteOutcome::Written(path.to_owned()))
}

/// Copy a foreign file to the first free `<name>.bak[.N]` beside it.
fn backup(path: &Path) -> io::Result<()> {
    let file_name = path
        .file_name()
        .map(|name| name.to_string_lossy().into_owned())
        .unwrap_or_default();
    let mut candidate = path.with_file_name(format!("{file_name}.bak"));
    let mut n = 0u32;
    while candidate.exists() {
        n += 1;
        if n > 999 {
            return Err(io::Error::new(
                io::ErrorKind::AlreadyExists,
                "too many xremap config backups",
            ));
        }
        candidate = path.with_file_name(format!("{file_name}.bak.{n}"));
    }
    fs::copy(path, &candidate)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn map(
        code: &str,
        tap: Option<&str>,
        hold: Option<&str>,
        device: &str,
        swap: bool,
    ) -> (String, Mapping) {
        (
            code.to_owned(),
            Mapping {
                tap: tap.map(str::to_owned),
                hold: hold.map(str::to_owned),
                device: device.to_owned(),
                swap,
            },
        )
    }

    fn no_devices(id: &str) -> String {
        id.to_owned()
    }

    /// Tap/hold, swap, disabled, and device-scoped mappings in one
    /// document — every construct the generator can emit.
    fn representative_maps() -> Maps {
        vec![
            map("CapsLock", Some("Escape"), Some("Control"), "all", false),
            map("ControlLeft", Some("Left Alt"), None, "all", true),
            map("MetaLeft", Some("Disabled"), None, "all", false),
            map("F12", Some("Play/Pause"), None, "kb1", false),
        ]
    }

    #[test]
    fn key_symbols_derive_from_evdev() {
        assert_eq!(key_symbol("CapsLock").as_deref(), Some("KEY_CAPSLOCK"));
        assert_eq!(key_symbol("ControlRight").as_deref(), Some("KEY_RIGHTCTRL"));
        assert_eq!(key_symbol("Numpad7").as_deref(), Some("KEY_KP7"));
        assert_eq!(key_symbol("NoSuchKey"), None);
    }

    #[test]
    fn every_catalog_action_translates_except_hyper_and_disabled() {
        for (_, actions) in model::ACTION_GROUPS {
            for action in *actions {
                let symbol = action_symbol(action);
                if *action == "Hyper" || *action == "Disabled" {
                    assert_eq!(symbol, None, "{action} has no key");
                } else {
                    assert!(symbol.is_some(), "{action} should translate");
                }
            }
        }
    }

    #[test]
    fn every_deck_key_action_name_translates() {
        for cap in model::registry() {
            let action = model::key_name(cap.code);
            assert!(
                action_symbol(&action).is_some(),
                "captured output {action} should translate"
            );
        }
    }

    /// The output picker must offer every key the app renders, under
    /// exactly the name `key_name` produces (so selection, generation,
    /// and the self-mapping check all agree).
    #[test]
    fn catalog_offers_every_deck_key() {
        for cap in model::registry() {
            let name = model::key_name(cap.code);
            let offered = model::ACTION_GROUPS
                .iter()
                .any(|(_, actions)| actions.iter().any(|action| *action == name));
            assert!(
                offered,
                "{name} ({}) is missing from the action catalog",
                cap.code
            );
        }
    }

    #[test]
    fn simple_remap_is_deterministic() {
        let maps = vec![
            map("AltRight", Some("Right Control"), None, "all", false),
            map("CapsLock", Some("Escape"), None, "all", false),
        ];
        let expected = format!(
            "{MARKER}\n\
             modmap:\n\
             \x20 - name: Keyloom mappings\n\
             \x20   remap:\n\
             \x20     KEY_CAPSLOCK: KEY_ESC\n\
             \x20     KEY_RIGHTALT: KEY_RIGHTCTRL\n"
        );
        assert_eq!(generate(&maps, no_devices), expected);
        // Insertion order does not change the output.
        let reversed: Maps = maps.into_iter().rev().collect();
        assert_eq!(generate(&reversed, no_devices), expected);
    }

    #[test]
    fn tap_hold_emits_held_and_alone() {
        let maps = vec![map(
            "CapsLock",
            Some("Escape"),
            Some("Control"),
            "all",
            false,
        )];
        let yaml = generate(&maps, no_devices);
        assert!(
            yaml.contains(
                "      KEY_CAPSLOCK:\n        held: KEY_LEFTCTRL\n        alone: KEY_ESC\n"
            )
        );
    }

    #[test]
    fn hold_only_keeps_tap_as_the_key_itself() {
        let maps = vec![map("CapsLock", None, Some("Control"), "all", false)];
        let yaml = generate(&maps, no_devices);
        assert!(yaml.contains("        held: KEY_LEFTCTRL\n        alone: KEY_CAPSLOCK\n"));
    }

    #[test]
    fn disabled_key_emits_no_output() {
        let maps = vec![map("MetaLeft", Some("Disabled"), None, "all", false)];
        let yaml = generate(&maps, no_devices);
        assert!(yaml.contains("      KEY_LEFTMETA: []\n"));
    }

    #[test]
    fn swap_generates_both_directions() {
        let maps = vec![map("ControlLeft", Some("Left Alt"), None, "all", true)];
        let yaml = generate(&maps, no_devices);
        assert!(yaml.contains("      KEY_LEFTALT: KEY_LEFTCTRL\n"));
        assert!(yaml.contains("      KEY_LEFTCTRL: KEY_LEFTALT\n"));
    }

    #[test]
    fn explicit_mapping_beats_swap_reverse() {
        let maps = vec![
            map("ControlLeft", Some("Left Alt"), None, "all", true),
            map("AltLeft", Some("Escape"), None, "all", false),
        ];
        let yaml = generate(&maps, no_devices);
        assert!(yaml.contains("      KEY_LEFTALT: KEY_ESC\n"));
        assert!(!yaml.contains("      KEY_LEFTALT: KEY_LEFTCTRL\n"));
    }

    #[test]
    fn untranslatable_hold_falls_back_to_simple_remap() {
        let maps = vec![map("CapsLock", Some("Escape"), Some("Hyper"), "all", false)];
        let yaml = generate(&maps, no_devices);
        assert!(yaml.contains("      KEY_CAPSLOCK: KEY_ESC\n"));
        assert!(!yaml.contains("held"));
    }

    #[test]
    fn device_scopes_become_filtered_blocks() {
        let maps = vec![
            map("CapsLock", Some("Escape"), None, "all", false),
            map("MetaLeft", Some("Alt"), None, "kb1", false),
        ];
        let yaml = generate(&maps, |id| {
            if id == "kb1" {
                "Keychron K2 Pro".to_owned()
            } else {
                id.to_owned()
            }
        });
        let scoped = yaml
            .find("Keyloom mappings (Keychron K2 Pro)")
            .expect("scoped block");
        let unscoped = yaml.find("name: Keyloom mappings\n").expect("all block");
        assert!(unscoped < scoped, "unscoped block comes first");
        assert!(yaml.contains("    device:\n      only: ['Keychron K2 Pro']\n"));
    }

    #[test]
    fn empty_mappings_generate_an_empty_modmap() {
        let yaml = generate(&Vec::new(), no_devices);
        assert_eq!(yaml, format!("{MARKER}\nmodmap: []\n"));
    }

    /// Golden document covering every generated construct at once; the
    /// same content is validated against a real xremap release by
    /// `generated_documents_parse_with_real_xremap`.
    #[test]
    fn representative_document_matches_golden_output() {
        let yaml = generate(&representative_maps(), |id| {
            if id == "kb1" {
                "Keychron K2 Pro".to_owned()
            } else {
                id.to_owned()
            }
        });
        let expected = format!(
            "{MARKER}\n\
             modmap:\n\
             \x20 - name: Keyloom mappings\n\
             \x20   remap:\n\
             \x20     KEY_CAPSLOCK:\n\
             \x20       held: KEY_LEFTCTRL\n\
             \x20       alone: KEY_ESC\n\
             \x20     KEY_LEFTALT: KEY_LEFTCTRL\n\
             \x20     KEY_LEFTCTRL: KEY_LEFTALT\n\
             \x20     KEY_LEFTMETA: []\n\
             \x20 - name: 'Keyloom mappings (Keychron K2 Pro)'\n\
             \x20   device:\n\
             \x20     only: ['Keychron K2 Pro']\n\
             \x20   remap:\n\
             \x20     KEY_F12: KEY_PLAYPAUSE\n"
        );
        assert_eq!(yaml, expected);
    }

    #[test]
    fn write_respects_foreign_files_and_backs_them_up() {
        let dir = std::env::temp_dir().join(format!("keyloom-test-{}", std::process::id()));
        fs::create_dir_all(&dir).unwrap();
        let path = dir.join("config.yml");
        let ours = generate(&Vec::new(), no_devices);

        // Fresh write, then an identical write is a no-op.
        assert_eq!(
            write_to(&path, &ours, false).unwrap(),
            WriteOutcome::Written(path.clone())
        );
        assert_eq!(
            write_to(&path, &ours, false).unwrap(),
            WriteOutcome::Unchanged(path.clone())
        );

        // A hand-written file is preserved unless overwriting is allowed.
        fs::write(&path, "modmap: [] # hand written\n").unwrap();
        let updated = format!("{ours}# updated\n");
        assert_eq!(
            write_to(&path, &updated, false).unwrap(),
            WriteOutcome::SkippedForeign(path.clone())
        );
        assert_eq!(
            write_to(&path, &updated, true).unwrap(),
            WriteOutcome::Written(path.clone())
        );
        assert_eq!(fs::read_to_string(&path).unwrap(), updated);
        assert_eq!(
            fs::read_to_string(dir.join("config.yml.bak")).unwrap(),
            "modmap: [] # hand written\n"
        );

        // Our own older output is replaced without a backup.
        assert_eq!(
            write_to(&path, &ours, false).unwrap(),
            WriteOutcome::Written(path.clone())
        );
        assert!(!dir.join("config.yml.bak.1").exists());

        fs::remove_dir_all(&dir).unwrap();
    }

    /// End-to-end oracle against a real xremap binary: the pinned CLI
    /// loads its configuration *before* selecting devices, so pointing
    /// it at a device name that cannot exist distinguishes "config
    /// parsed" (fails preparing input devices) from "config rejected"
    /// (fails loading the config).
    ///
    /// Ignored during normal local tests to avoid launching the installed
    /// xremap. CI installs the pinned release and explicitly runs this test
    /// with `--ignored`; a missing binary is a failure.
    #[test]
    #[ignore = "launches xremap; CI runs this explicitly with a pinned binary"]
    fn generated_documents_parse_with_real_xremap() {
        use std::process::Command;

        // Every known physical key as a remap source.
        let sources: Vec<&str> = model::registry().map(|cap| cap.code).collect();
        let all_sources: Maps = sources
            .iter()
            .map(|code| map(code, Some("Escape"), None, "all", false))
            .collect();
        // Every translatable catalog action as an output (plus
        // Disabled; Hyper has no key and is dropped by the generator).
        // The catalog holds more actions than there are keys, so cycle
        // sources; one source keeps only its last action, which is fine
        // because every action still appears in some document chunk
        // below.
        let actions: Vec<&&str> = model::ACTION_GROUPS
            .iter()
            .flat_map(|(_, actions)| actions.iter())
            .collect();
        let all_action_chunks: Vec<Maps> = actions
            .chunks(sources.len())
            .map(|chunk| {
                chunk
                    .iter()
                    .enumerate()
                    .map(|(i, action)| map(sources[i], Some(action), None, "all", false))
                    .collect()
            })
            .collect();

        let mut documents = vec![
            ("empty".to_owned(), generate(&Vec::new(), no_devices)),
            (
                "representative".to_owned(),
                generate(&representative_maps(), |id| {
                    if id == "kb1" {
                        "Keychron K2 Pro".to_owned()
                    } else {
                        id.to_owned()
                    }
                }),
            ),
            ("all-sources".to_owned(), generate(&all_sources, no_devices)),
        ];
        for (i, chunk) in all_action_chunks.iter().enumerate() {
            documents.push((format!("all-actions-{i}"), generate(chunk, no_devices)));
        }

        let dir = std::env::temp_dir().join(format!("keyloom-xremap-{}", std::process::id()));
        fs::create_dir_all(&dir).unwrap();
        for (name, yaml) in &documents {
            let path = dir.join(format!("{name}.yml"));
            fs::write(&path, yaml).unwrap();
            let output = Command::new("xremap")
                .arg("--device")
                .arg("keyloom-validation-no-such-device")
                .arg(&path)
                .output()
                .expect("xremap validation requires the pinned binary on PATH");
            let stderr = String::from_utf8_lossy(&output.stderr);
            assert!(
                !stderr.contains("Failed to load config"),
                "{name}: xremap rejected the generated config:\n{stderr}\n---\n{yaml}"
            );
            assert!(
                stderr.contains("Failed to prepare input devices"),
                "{name}: xremap did not reach device selection:\n{stderr}"
            );
        }
        fs::remove_dir_all(&dir).unwrap();
    }
}
