//! Translation layer from Keyloom's internal mapping model to a valid
//! xremap configuration file.
//!
//! The rule model in [`crate::ui::model`] is the source of truth; the
//! YAML written to the user's config directory is generated output.
//! Generation is deterministic: identical mappings always produce
//! byte-identical YAML, with sources sorted by their xremap key name.
//!
//! Mappings become `modmap` entries. Layers become `keymap` rules
//! guarded by a virtual modifier that stands in for the held layer key
//! (see [`LAYER_MODIFIERS`]).

use std::collections::{BTreeMap, HashMap};
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use evdev::KeyCode;

use crate::ui::model::{self, Layer, Mapping, Maps};

/// First line of every file Keyloom generates. Files that don't start
/// with this marker are treated as foreign and never silently replaced.
const MARKER: &str = "# Generated by Keyloom. Do not edit by hand; Keyloom overwrites this file.";

/// Stand-ins for held layer keys. xremap treats a key listed under
/// `virtual_modifiers` as a modifier for `keymap` rules and never sends
/// it on, so each layer's key is remapped to one of these and the
/// layer's rules match on it. Braille-dot codes are used because no
/// keyboard emits them: nothing but the layer key can activate a layer.
/// The pool caps how many layers a profile can generate rules for.
const LAYER_MODIFIERS: [&str; 10] = [
    "KEY_BRL_DOT1",
    "KEY_BRL_DOT2",
    "KEY_BRL_DOT3",
    "KEY_BRL_DOT4",
    "KEY_BRL_DOT5",
    "KEY_BRL_DOT6",
    "KEY_BRL_DOT7",
    "KEY_BRL_DOT8",
    "KEY_BRL_DOT9",
    "KEY_BRL_DOT10",
];

/// How many layers one profile can generate rules for.
pub const MAX_LAYERS: usize = LAYER_MODIFIERS.len();

/// Whether a deck key is one of the physical modifiers (Shift, Control,
/// Alt, Super). xremap always passes those through, so they cannot take
/// on a job inside a layer.
pub fn is_modifier_key(code: &str) -> bool {
    const MODIFIERS: [KeyCode; 8] = [
        KeyCode::KEY_LEFTSHIFT,
        KeyCode::KEY_RIGHTSHIFT,
        KeyCode::KEY_LEFTCTRL,
        KeyCode::KEY_RIGHTCTRL,
        KeyCode::KEY_LEFTALT,
        KeyCode::KEY_RIGHTALT,
        KeyCode::KEY_LEFTMETA,
        KeyCode::KEY_RIGHTMETA,
    ];
    model::key(code).is_some_and(|cap| MODIFIERS.contains(&KeyCode(cap.evdev)))
}

/// xremap key name (`KEY_*`) for a physical key on the deck, derived
/// from its evdev scancode.
pub fn key_symbol(code: &str) -> Option<String> {
    model::key(code).and_then(|cap| evdev_name(cap.evdev))
}

/// xremap key name (`KEY_*`) for an action from the editor's catalog
/// (e.g. `Escape`, `Right Control`, `Play/Pause`).
///
/// Returns `None` for actions with no evdev key, such as `Hyper` and
/// `Disabled` (the generator handles `Disabled` itself).
pub fn action_symbol(action: &str) -> Option<String> {
    // Actions named after a physical key ("Caps Lock", "Right Control",
    // "Numpad 7", "ISO Backslash", …) resolve through its scancode.
    if let Some(cap) = model::registry().find(|cap| model::key_name(cap.code) == action) {
        return evdev_name(cap.evdev);
    }
    // Catalog names that differ from the deck's key names, plus keys
    // that have no cap on the rendered keyboard (media, brightness).
    const ACTIONS: &[(&str, &str)] = &[
        ("Control", "KEY_LEFTCTRL"),
        ("Shift", "KEY_LEFTSHIFT"),
        ("Alt", "KEY_LEFTALT"),
        ("Super", "KEY_LEFTMETA"),
        ("Left", "KEY_LEFT"),
        ("Right", "KEY_RIGHT"),
        ("Up", "KEY_UP"),
        ("Down", "KEY_DOWN"),
        ("Bracket Left", "KEY_LEFTBRACE"),
        ("Bracket Right", "KEY_RIGHTBRACE"),
        ("Play/Pause", "KEY_PLAYPAUSE"),
        ("Next", "KEY_NEXTSONG"),
        ("Previous", "KEY_PREVIOUSSONG"),
        ("Mute", "KEY_MUTE"),
        ("Volume Up", "KEY_VOLUMEUP"),
        ("Volume Down", "KEY_VOLUMEDOWN"),
        ("Brightness Up", "KEY_BRIGHTNESSUP"),
        ("Brightness Down", "KEY_BRIGHTNESSDOWN"),
    ];
    ACTIONS
        .iter()
        .find(|(name, _)| *name == action)
        .map(|(_, symbol)| (*symbol).to_owned())
}

/// Canonical evdev name for a scancode (`KEY_CAPSLOCK`), which xremap
/// accepts directly. `None` for codes evdev has no name for.
fn evdev_name(scancode: u16) -> Option<String> {
    let name = format!("{:?}", KeyCode(scancode));
    name.starts_with("KEY_").then_some(name)
}

/// What a source key produces in the generated modmap.
#[derive(Clone, Debug, PartialEq, Eq)]
enum Output {
    /// Simple remap to one key.
    Key(String),
    /// Key emits nothing (`Disabled` in the editor).
    Disabled,
    /// Tap/hold multi-purpose key. `None` slots emit nothing.
    TapHold {
        alone: Option<String>,
        held: Option<String>,
    },
}

/// What a mapping slot turns into: `Some(None)` disables it,
/// `Some(Some(_))` remaps it, and `None` leaves it alone because it is
/// unset or holds an untranslatable action (e.g. `Hyper`).
fn slot(action: Option<&str>) -> Option<Option<String>> {
    match action {
        Some("Disabled") => Some(None),
        Some(action) => action_symbol(action).map(Some),
        None => None,
    }
}

/// Resolve one mapping into `(source symbol, output)`, or `None` when
/// nothing about it can be expressed as an xremap rule.
///
/// A key that holds a layer produces the layer's modifier while held:
/// its tap action keeps working through a tap/hold key, and any hold
/// action is superseded by the layer.
fn resolve(
    code: &str,
    mapping: &Mapping,
    layer_modifier: Option<&str>,
) -> Option<(String, Output)> {
    let source = key_symbol(code)?;
    let tap = slot(mapping.tap.as_deref());
    let output = if let Some(modifier) = layer_modifier {
        match tap {
            Some(Some(key)) => Output::TapHold {
                alone: Some(key),
                held: Some(modifier.to_owned()),
            },
            _ => Output::Key(modifier.to_owned()),
        }
    } else {
        match slot(mapping.hold.as_deref()) {
            Some(held) => Output::TapHold {
                // Tapping falls back to the key's own behavior when only
                // a hold action is configured (xremap requires `alone`).
                alone: tap.unwrap_or(Some(source.clone())),
                held,
            },
            None => match tap {
                Some(None) => Output::Disabled,
                Some(Some(key)) => Output::Key(key),
                None => return None,
            },
        }
    };
    Some((source, output))
}

/// Layer key code → the modifier standing in for it.
type Triggers<'a> = HashMap<&'a str, &'static str>;

/// Entries for one device scope, sorted by source symbol.
fn scope_entries(mappings: &[&(String, Mapping)], triggers: &Triggers) -> BTreeMap<String, Output> {
    let mut entries = BTreeMap::new();
    // Explicit mappings first; the model keeps one mapping per key.
    for (code, mapping) in mappings {
        let modifier = triggers.get(code.as_str()).copied();
        if let Some((source, output)) = resolve(code, mapping, modifier) {
            entries.entry(source).or_insert(output);
        }
    }
    // Two-way swaps add the reverse entry unless the reverse source
    // already has an explicit mapping.
    for (code, mapping) in mappings {
        if !mapping.swap || mapping.hold.is_some() {
            continue;
        }
        let (Some(source), Some(tap)) = (key_symbol(code), mapping.tap.as_deref()) else {
            continue;
        };
        if let Some(reverse) = action_symbol(tap)
            && reverse != source
        {
            entries.entry(reverse).or_insert(Output::Key(source));
        }
    }
    entries
}

/// Single-quote a YAML scalar (device names may contain anything).
fn quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

/// A device scope: `None` is every keyboard (`all`), `Some((resolved
/// name, id))` a specific one.
type Scope = Option<(String, String)>;

fn scope_of(device: &str, device_name: &impl Fn(&str) -> String) -> Scope {
    match device {
        "" | "all" => None,
        id => Some((device_name(id), id.to_owned())),
    }
}

/// Blocks for specific keyboards, sorted by name, then the block for
/// every keyboard. xremap uses the first block that mentions a key, so
/// the general block must not shadow a keyboard's own entry.
fn ordered<T>(by_scope: &BTreeMap<Scope, T>) -> impl Iterator<Item = (&Scope, &T)> {
    let specific = by_scope.iter().filter(|(scope, _)| scope.is_some());
    let general = by_scope.iter().filter(|(scope, _)| scope.is_none());
    specific.chain(general)
}

/// The `name:` line of a block, plus its device filter for a specific
/// keyboard.
fn block_header(title: &str, scope: &Scope) -> String {
    match scope {
        None => format!("  - name: {}\n", quote(title)),
        Some((name, _)) => format!(
            "  - name: {}\n    device:\n      only: [{}]\n",
            quote(&format!("{title} ({name})")),
            quote(name)
        ),
    }
}

/// One `modmap` block.
fn modmap_block(scope: &Scope, entries: &BTreeMap<String, Output>) -> String {
    let mut block = block_header("Keyloom mappings", scope);
    block.push_str("    remap:\n");
    for (source, output) in entries {
        match output {
            Output::Key(key) => block.push_str(&format!("      {source}: {key}\n")),
            Output::Disabled => block.push_str(&format!("      {source}: []\n")),
            Output::TapHold { alone, held } => {
                let slot = |slot: &Option<String>| slot.clone().unwrap_or_else(|| "[]".to_owned());
                block.push_str(&format!("      {source}:\n"));
                block.push_str(&format!("        held: {}\n", slot(held)));
                block.push_str(&format!("        alone: {}\n", slot(alone)));
            }
        }
    }
    block
}

/// A layer whose key is a known deck key, with the modifier standing
/// in for it.
struct ResolvedLayer<'a> {
    layer: &'a Layer,
    /// The layer key's own symbol.
    trigger: String,
    modifier: &'static str,
}

/// Layers that can generate rules, in profile order. Layers whose key
/// is unset or unknown, and layers beyond the modifier pool, are left
/// out.
fn resolve_layers(layers: &[Layer]) -> Vec<ResolvedLayer<'_>> {
    layers
        .iter()
        .filter_map(|layer| key_symbol(&layer.trigger).map(|trigger| (layer, trigger)))
        .zip(LAYER_MODIFIERS)
        .map(|((layer, trigger), modifier)| ResolvedLayer {
            layer,
            trigger,
            modifier,
        })
        .collect()
}

/// The symbol a key's press reaches the rules with, per scope a layer
/// job applies to. Mappings run first, so a key whose tap is remapped
/// arrives as its tap action; a key whose tap is disabled never arrives
/// at all. A mapping scoped to one keyboard while the job applies
/// everywhere adds a refined source for that keyboard.
fn rule_sources(
    code: &str,
    scope: &Scope,
    maps: &Maps,
    device_name: &impl Fn(&str) -> String,
) -> Vec<(Scope, String)> {
    let Some(source) = key_symbol(code) else {
        return Vec::new();
    };
    let Some((_, mapping)) = maps.iter().find(|(key, _)| key == code) else {
        return vec![(scope.clone(), source)];
    };
    let mapped = match slot(mapping.tap.as_deref()) {
        Some(None) => None,
        Some(Some(key)) => Some(key),
        // Hold-only and dropped mappings leave the tap as the key itself.
        None => Some(source.clone()),
    };
    let mapping_scope = scope_of(&mapping.device, device_name);
    if mapping_scope.is_none() || mapping_scope == *scope {
        return mapped.map(|key| (scope.clone(), key)).into_iter().collect();
    }
    let mut sources = vec![(scope.clone(), source)];
    if scope.is_none()
        && let Some(key) = mapped
    {
        sources.push((mapping_scope, key));
    }
    sources
}

/// The `keymap` blocks for one layer, one per device scope.
fn layer_blocks(
    layer: &ResolvedLayer<'_>,
    maps: &Maps,
    triggers: &Triggers,
    device_name: &impl Fn(&str) -> String,
) -> Vec<String> {
    // Source symbol → output (`None` emits nothing), per scope.
    let mut rules: BTreeMap<Scope, BTreeMap<String, Option<String>>> = BTreeMap::new();
    for key in &layer.layer.keys {
        // A layer key is remapped before the rules see it, and physical
        // modifiers always pass through: neither can take a job.
        if triggers.contains_key(key.code.as_str()) || is_modifier_key(&key.code) {
            continue;
        }
        let output = match key.action.as_str() {
            "Disabled" => None,
            action => match action_symbol(action) {
                Some(symbol) => Some(symbol),
                None => continue,
            },
        };
        let scope = scope_of(&key.device, device_name);
        for (scope, source) in rule_sources(&key.code, &scope, maps, device_name) {
            rules
                .entry(scope)
                .or_default()
                .entry(source)
                .or_insert_with(|| output.clone());
        }
    }

    let title = format!(
        "Keyloom layer: {}, hold {}",
        layer.layer.name,
        model::key_name(&layer.layer.trigger)
    );
    ordered(&rules)
        .filter(|(_, rules)| !rules.is_empty())
        .map(|(scope, rules)| {
            let mut block = block_header(&title, scope);
            block.push_str("    remap:\n");
            for (source, output) in rules {
                let modifier = layer.modifier;
                match output {
                    Some(key) => block.push_str(&format!("      {modifier}-{source}: {key}\n")),
                    None => block.push_str(&format!("      {modifier}-{source}: []\n")),
                }
            }
            block
        })
        .collect()
}

/// Render the active profile's mappings and layers as a complete xremap
/// document.
///
/// `device_name` resolves a device scope id to the display name xremap
/// should match on. Blocks for specific keyboards come first, sorted by
/// resolved name, then the block for every keyboard.
pub fn generate(maps: &Maps, layers: &[Layer], device_name: impl Fn(&str) -> String) -> String {
    let layers = resolve_layers(layers);
    let triggers: Triggers = layers
        .iter()
        .map(|layer| (layer.layer.trigger.as_str(), layer.modifier))
        .collect();

    // Group mappings by device scope.
    let mut scopes: BTreeMap<Scope, Vec<&(String, Mapping)>> = BTreeMap::new();
    for entry in maps {
        scopes
            .entry(scope_of(&entry.1.device, &device_name))
            .or_default()
            .push(entry);
    }
    let mut modmaps: BTreeMap<Scope, BTreeMap<String, Output>> = scopes
        .iter()
        .map(|(scope, mappings)| (scope.clone(), scope_entries(mappings, &triggers)))
        .collect();
    // A layer key produces its modifier on every keyboard; a mapping
    // of that key scoped to one keyboard refines it there.
    for layer in &layers {
        modmaps
            .entry(None)
            .or_default()
            .entry(layer.trigger.clone())
            .or_insert(Output::Key(layer.modifier.to_owned()));
    }

    let mut yaml = format!("{MARKER}\n");
    let blocks: Vec<String> = ordered(&modmaps)
        .filter(|(_, entries)| !entries.is_empty())
        .map(|(scope, entries)| modmap_block(scope, entries))
        .collect();
    if blocks.is_empty() {
        yaml.push_str("modmap: []\n");
    } else {
        yaml.push_str("modmap:\n");
        for block in blocks {
            yaml.push_str(&block);
        }
    }

    if !layers.is_empty() {
        yaml.push_str("virtual_modifiers:\n");
        for layer in &layers {
            yaml.push_str(&format!("  - {}\n", layer.modifier));
        }
    }
    let blocks: Vec<String> = layers
        .iter()
        .flat_map(|layer| layer_blocks(layer, maps, &triggers, &device_name))
        .collect();
    if !blocks.is_empty() {
        yaml.push_str("keymap:\n");
        for block in blocks {
            yaml.push_str(&block);
        }
    }
    yaml
}

/// Result of writing the generated configuration.
#[derive(Debug, PartialEq, Eq)]
pub enum WriteOutcome {
    /// File created or replaced.
    Written(PathBuf),
    /// File already had exactly this content.
    Unchanged(PathBuf),
    /// An existing file without the Keyloom marker was left untouched.
    SkippedForeign(PathBuf),
}

/// The user's configuration directory: `$XDG_CONFIG_HOME`, or
/// `~/.config` when that is unset.
pub(crate) fn config_home() -> Option<PathBuf> {
    std::env::var_os("XDG_CONFIG_HOME")
        .filter(|dir| !dir.is_empty())
        .map(PathBuf::from)
        .filter(|dir| dir.is_absolute())
        .or_else(|| {
            std::env::var_os("HOME")
                .filter(|home| !home.is_empty())
                .map(|home| PathBuf::from(home).join(".config"))
        })
}

/// Where the generated configuration lives:
/// `$XDG_CONFIG_HOME/xremap/keyloom.yml` (usually `~/.config`).
pub fn config_path() -> Option<PathBuf> {
    Some(config_home()?.join("xremap").join("keyloom.yml"))
}

/// Write the generated document to [`config_path`].
///
/// A pre-existing file that Keyloom did not generate is backed up
/// beside the original before being replaced when `overwrite_foreign`
/// is set, and left untouched otherwise.
pub fn write(yaml: &str, overwrite_foreign: bool) -> io::Result<WriteOutcome> {
    let path = config_path().ok_or_else(|| {
        io::Error::new(io::ErrorKind::NotFound, "no home directory to write into")
    })?;
    write_to(&path, yaml, overwrite_foreign)
}

/// [`write`] with an explicit target path.
pub fn write_to(path: &Path, yaml: &str, overwrite_foreign: bool) -> io::Result<WriteOutcome> {
    if let Ok(existing) = fs::read(path) {
        if existing == yaml.as_bytes() {
            return Ok(WriteOutcome::Unchanged(path.to_owned()));
        }
        if !existing.starts_with(MARKER.as_bytes()) {
            if !overwrite_foreign {
                return Ok(WriteOutcome::SkippedForeign(path.to_owned()));
            }
            backup(path)?;
        }
    }
    let dir = path
        .parent()
        .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidInput, "config path has no parent"))?;
    fs::create_dir_all(dir)?;
    // Write-then-rename so a watching xremap never sees a partial file.
    let tmp = path.with_extension("yml.tmp");
    fs::write(&tmp, yaml)?;
    fs::rename(&tmp, path)?;
    Ok(WriteOutcome::Written(path.to_owned()))
}

/// Copy a foreign file to the first free `<name>.bak[.N]` beside it.
pub(crate) fn backup(path: &Path) -> io::Result<()> {
    let file_name = path
        .file_name()
        .map(|name| name.to_string_lossy().into_owned())
        .unwrap_or_default();
    let mut candidate = path.with_file_name(format!("{file_name}.bak"));
    let mut n = 0u32;
    while candidate.exists() {
        n += 1;
        if n > 999 {
            return Err(io::Error::new(
                io::ErrorKind::AlreadyExists,
                "too many xremap config backups",
            ));
        }
        candidate = path.with_file_name(format!("{file_name}.bak.{n}"));
    }
    fs::copy(path, &candidate)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::str::FromStr;

    use super::*;
    use crate::testing::TempDir;
    use crate::ui::model::LayerKey;

    fn map(
        code: &str,
        tap: Option<&str>,
        hold: Option<&str>,
        device: &str,
        swap: bool,
    ) -> (String, Mapping) {
        (
            code.to_owned(),
            Mapping {
                tap: tap.map(str::to_owned),
                hold: hold.map(str::to_owned),
                device: device.to_owned(),
                swap,
            },
        )
    }

    /// A layer from `(key code, action, device scope)` jobs.
    fn layer(id: &str, trigger: &str, keys: &[(&str, &str, &str)]) -> Layer {
        Layer {
            id: id.to_owned(),
            name: id.to_owned(),
            trigger: trigger.to_owned(),
            keys: keys
                .iter()
                .map(|(code, action, device)| LayerKey {
                    code: (*code).to_owned(),
                    action: (*action).to_owned(),
                    device: (*device).to_owned(),
                })
                .collect(),
        }
    }

    fn no_devices(id: &str) -> String {
        id.to_owned()
    }

    fn kb1_named(id: &str) -> String {
        if id == "kb1" {
            "Keychron K2 Pro".to_owned()
        } else {
            id.to_owned()
        }
    }

    /// Generate without layers.
    fn without_layers(maps: &Maps) -> String {
        generate(maps, &[], no_devices)
    }

    /// Tap/hold, swap, disabled, and device-scoped mappings in one
    /// document — every mapping construct the generator can emit.
    fn representative_maps() -> Maps {
        vec![
            map("CapsLock", Some("Escape"), Some("Control"), "all", false),
            map("ControlLeft", Some("Left Alt"), None, "all", true),
            map("MetaLeft", Some("Disabled"), None, "all", false),
            map("F12", Some("Play/Pause"), None, "kb1", false),
        ]
    }

    /// A layer on the tap/hold Caps Lock of [`representative_maps`],
    /// with a remapped, a disabled, and a device-scoped job.
    fn representative_layers() -> Vec<Layer> {
        vec![Layer {
            name: "Navigation".to_owned(),
            ..layer(
                "nav",
                "CapsLock",
                &[
                    ("KeyH", "Arrow Left", "all"),
                    ("KeyY", "Disabled", "all"),
                    ("KeyJ", "Arrow Down", "kb1"),
                ],
            )
        }]
    }

    #[test]
    fn key_symbols_derive_from_evdev() {
        assert_eq!(key_symbol("CapsLock").as_deref(), Some("KEY_CAPSLOCK"));
        assert_eq!(key_symbol("ControlRight").as_deref(), Some("KEY_RIGHTCTRL"));
        assert_eq!(key_symbol("Numpad7").as_deref(), Some("KEY_KP7"));
        assert_eq!(key_symbol("NoSuchKey"), None);
    }

    #[test]
    fn every_catalog_action_translates_except_hyper_and_disabled() {
        for (_, actions) in model::ACTION_GROUPS {
            for action in *actions {
                let symbol = action_symbol(action);
                if *action == "Hyper" || *action == "Disabled" {
                    assert_eq!(symbol, None, "{action} has no key");
                } else {
                    assert!(symbol.is_some(), "{action} should translate");
                }
            }
        }
    }

    #[test]
    fn every_deck_key_action_name_translates() {
        for cap in model::registry() {
            let action = model::key_name(cap.code);
            assert!(
                action_symbol(&action).is_some(),
                "captured output {action} should translate"
            );
        }
    }

    /// The output picker must offer every key the app renders, under
    /// exactly the name `key_name` produces (so selection, generation,
    /// and the self-mapping check all agree).
    #[test]
    fn catalog_offers_every_deck_key() {
        for cap in model::registry() {
            let name = model::key_name(cap.code);
            let offered = model::ACTION_GROUPS
                .iter()
                .any(|(_, actions)| actions.iter().any(|action| *action == name));
            assert!(
                offered,
                "{name} ({}) is missing from the action catalog",
                cap.code
            );
        }
    }

    #[test]
    fn simple_remap_is_deterministic() {
        let maps = vec![
            map("AltRight", Some("Right Control"), None, "all", false),
            map("CapsLock", Some("Escape"), None, "all", false),
        ];
        let expected = format!(
            "{MARKER}\n\
             modmap:\n\
             \x20 - name: 'Keyloom mappings'\n\
             \x20   remap:\n\
             \x20     KEY_CAPSLOCK: KEY_ESC\n\
             \x20     KEY_RIGHTALT: KEY_RIGHTCTRL\n"
        );
        assert_eq!(without_layers(&maps), expected);
        // Insertion order does not change the output.
        let reversed: Maps = maps.into_iter().rev().collect();
        assert_eq!(without_layers(&reversed), expected);
    }

    #[test]
    fn tap_hold_emits_held_and_alone() {
        let maps = vec![map(
            "CapsLock",
            Some("Escape"),
            Some("Control"),
            "all",
            false,
        )];
        let yaml = without_layers(&maps);
        assert!(
            yaml.contains(
                "      KEY_CAPSLOCK:\n        held: KEY_LEFTCTRL\n        alone: KEY_ESC\n"
            )
        );
    }

    #[test]
    fn hold_only_keeps_tap_as_the_key_itself() {
        let maps = vec![map("CapsLock", None, Some("Control"), "all", false)];
        let yaml = without_layers(&maps);
        assert!(yaml.contains("        held: KEY_LEFTCTRL\n        alone: KEY_CAPSLOCK\n"));
    }

    #[test]
    fn disabled_key_emits_no_output() {
        let maps = vec![map("MetaLeft", Some("Disabled"), None, "all", false)];
        let yaml = without_layers(&maps);
        assert!(yaml.contains("      KEY_LEFTMETA: []\n"));
    }

    #[test]
    fn swap_generates_both_directions() {
        let maps = vec![map("ControlLeft", Some("Left Alt"), None, "all", true)];
        let yaml = without_layers(&maps);
        assert!(yaml.contains("      KEY_LEFTALT: KEY_LEFTCTRL\n"));
        assert!(yaml.contains("      KEY_LEFTCTRL: KEY_LEFTALT\n"));
    }

    #[test]
    fn explicit_mapping_beats_swap_reverse() {
        let maps = vec![
            map("ControlLeft", Some("Left Alt"), None, "all", true),
            map("AltLeft", Some("Escape"), None, "all", false),
        ];
        let yaml = without_layers(&maps);
        assert!(yaml.contains("      KEY_LEFTALT: KEY_ESC\n"));
        assert!(!yaml.contains("      KEY_LEFTALT: KEY_LEFTCTRL\n"));
    }

    #[test]
    fn untranslatable_hold_falls_back_to_simple_remap() {
        let maps = vec![map("CapsLock", Some("Escape"), Some("Hyper"), "all", false)];
        let yaml = without_layers(&maps);
        assert!(yaml.contains("      KEY_CAPSLOCK: KEY_ESC\n"));
        assert!(!yaml.contains("held"));
    }

    /// xremap applies the first block that mentions a key, so a
    /// keyboard's own block has to come before the one for every
    /// keyboard.
    #[test]
    fn device_scopes_become_filtered_blocks_ahead_of_the_general_one() {
        let maps = vec![
            map("CapsLock", Some("Escape"), None, "all", false),
            map("MetaLeft", Some("Alt"), None, "kb1", false),
        ];
        let yaml = generate(&maps, &[], kb1_named);
        let scoped = yaml
            .find("'Keyloom mappings (Keychron K2 Pro)'")
            .expect("scoped block");
        let unscoped = yaml.find("name: 'Keyloom mappings'\n").expect("all block");
        assert!(scoped < unscoped, "the keyboard's own block comes first");
        assert!(yaml.contains("    device:\n      only: ['Keychron K2 Pro']\n"));
    }

    #[test]
    fn empty_mappings_generate_an_empty_modmap() {
        assert_eq!(
            without_layers(&Vec::new()),
            format!("{MARKER}\nmodmap: []\n")
        );
    }

    /// Golden document covering every generated construct at once; the
    /// same content is validated against a real xremap release by
    /// `generated_documents_parse_with_real_xremap`.
    #[test]
    fn representative_document_matches_golden_output() {
        let yaml = generate(&representative_maps(), &representative_layers(), kb1_named);
        let expected = format!(
            "{MARKER}\n\
             modmap:\n\
             \x20 - name: 'Keyloom mappings (Keychron K2 Pro)'\n\
             \x20   device:\n\
             \x20     only: ['Keychron K2 Pro']\n\
             \x20   remap:\n\
             \x20     KEY_F12: KEY_PLAYPAUSE\n\
             \x20 - name: 'Keyloom mappings'\n\
             \x20   remap:\n\
             \x20     KEY_CAPSLOCK:\n\
             \x20       held: KEY_BRL_DOT1\n\
             \x20       alone: KEY_ESC\n\
             \x20     KEY_LEFTALT: KEY_LEFTCTRL\n\
             \x20     KEY_LEFTCTRL: KEY_LEFTALT\n\
             \x20     KEY_LEFTMETA: []\n\
             virtual_modifiers:\n\
             \x20 - KEY_BRL_DOT1\n\
             keymap:\n\
             \x20 - name: 'Keyloom layer: Navigation, hold Caps Lock (Keychron K2 Pro)'\n\
             \x20   device:\n\
             \x20     only: ['Keychron K2 Pro']\n\
             \x20   remap:\n\
             \x20     KEY_BRL_DOT1-KEY_J: KEY_DOWN\n\
             \x20 - name: 'Keyloom layer: Navigation, hold Caps Lock'\n\
             \x20   remap:\n\
             \x20     KEY_BRL_DOT1-KEY_H: KEY_LEFT\n\
             \x20     KEY_BRL_DOT1-KEY_Y: []\n"
        );
        assert_eq!(yaml, expected);
    }

    // --- Layers ---------------------------------------------------------

    /// The stand-ins must be names xremap's evdev accepts, and none of
    /// them may be a key on the deck, or that key would activate the
    /// layer too.
    #[test]
    fn layer_modifiers_are_known_keys_off_the_deck() {
        for name in LAYER_MODIFIERS {
            let key = KeyCode::from_str(name).unwrap_or_else(|_| panic!("{name} is a key"));
            assert_eq!(evdev_name(key.0).as_deref(), Some(name));
            assert!(model::key_by_evdev(key.0).is_none(), "{name} is a deck key");
        }
        assert_eq!(MAX_LAYERS, LAYER_MODIFIERS.len());
    }

    #[test]
    fn modifier_keys_are_recognized() {
        for code in ["ShiftLeft", "ControlRight", "AltRight", "MetaLeft"] {
            assert!(is_modifier_key(code), "{code}");
        }
        for code in ["CapsLock", "Space", "Fn", "KeyA", "NoSuchKey"] {
            assert!(!is_modifier_key(code), "{code}");
        }
    }

    /// The simplest layer: the key becomes the layer's modifier and the
    /// jobs become rules on it. Tapping the key then does nothing.
    #[test]
    fn a_layer_key_becomes_a_virtual_modifier_with_rules() {
        let layers = vec![layer("nav", "CapsLock", &[("KeyH", "Arrow Left", "all")])];
        let yaml = generate(&Vec::new(), &layers, no_devices);
        let expected = format!(
            "{MARKER}\n\
             modmap:\n\
             \x20 - name: 'Keyloom mappings'\n\
             \x20   remap:\n\
             \x20     KEY_CAPSLOCK: KEY_BRL_DOT1\n\
             virtual_modifiers:\n\
             \x20 - KEY_BRL_DOT1\n\
             keymap:\n\
             \x20 - name: 'Keyloom layer: nav, hold Caps Lock'\n\
             \x20   remap:\n\
             \x20     KEY_BRL_DOT1-KEY_H: KEY_LEFT\n"
        );
        assert_eq!(yaml, expected);
    }

    /// A tap action on the layer key survives as the tap side of a
    /// tap/hold key whose hold side is the layer.
    #[test]
    fn a_layer_key_keeps_its_tap_action() {
        let maps = vec![map("CapsLock", Some("Escape"), None, "all", false)];
        let layers = vec![layer("nav", "CapsLock", &[("KeyH", "Arrow Left", "all")])];
        let yaml = generate(&maps, &layers, no_devices);
        assert!(
            yaml.contains(
                "      KEY_CAPSLOCK:\n        held: KEY_BRL_DOT1\n        alone: KEY_ESC\n"
            )
        );
        assert!(yaml.contains("      KEY_BRL_DOT1-KEY_H: KEY_LEFT\n"));
    }

    /// Holding the key now activates the layer; a hold action it had
    /// is superseded. A disabled or untranslatable tap adds nothing.
    #[test]
    fn a_layer_supersedes_the_layer_keys_hold_action() {
        let layers = vec![layer("nav", "CapsLock", &[("KeyH", "Arrow Left", "all")])];
        let maps = vec![map(
            "CapsLock",
            Some("Escape"),
            Some("Left Control"),
            "all",
            false,
        )];
        let yaml = generate(&maps, &layers, no_devices);
        assert!(yaml.contains("        held: KEY_BRL_DOT1\n        alone: KEY_ESC\n"));
        assert!(!yaml.contains("KEY_LEFTCTRL"));

        for tap in ["Disabled", "Hyper"] {
            let maps = vec![map(
                "CapsLock",
                Some(tap),
                Some("Left Control"),
                "all",
                false,
            )];
            let yaml = generate(&maps, &layers, no_devices);
            assert!(
                yaml.contains("      KEY_CAPSLOCK: KEY_BRL_DOT1\n"),
                "{tap}: {yaml}"
            );
            assert!(!yaml.contains("held"), "{tap}");
        }
    }

    /// Mappings apply before rules, so a job on a remapped key has to
    /// match what the key became. A key whose tap is disabled never
    /// reaches the rules; a hold-only key still arrives as itself.
    #[test]
    fn layer_rules_match_the_remapped_key() {
        let layers = vec![layer("nav", "CapsLock", &[("KeyH", "Arrow Left", "all")])];

        let maps = vec![map("KeyH", Some("J"), None, "all", false)];
        let yaml = generate(&maps, &layers, no_devices);
        assert!(yaml.contains("      KEY_BRL_DOT1-KEY_J: KEY_LEFT\n"));
        assert!(!yaml.contains("-KEY_H:"));

        let maps = vec![map("KeyH", Some("J"), Some("Left Control"), "all", false)];
        let yaml = generate(&maps, &layers, no_devices);
        assert!(yaml.contains("      KEY_BRL_DOT1-KEY_J: KEY_LEFT\n"));

        let maps = vec![map("KeyH", None, Some("Left Control"), "all", false)];
        let yaml = generate(&maps, &layers, no_devices);
        assert!(yaml.contains("      KEY_BRL_DOT1-KEY_H: KEY_LEFT\n"));

        let maps = vec![map("KeyH", Some("Disabled"), None, "all", false)];
        let yaml = generate(&maps, &layers, no_devices);
        assert!(!yaml.contains("keymap"), "{yaml}");
        assert!(
            yaml.contains("virtual_modifiers"),
            "the layer key still holds"
        );
    }

    /// A mapping scoped to one keyboard refines the job there while the
    /// general rule keeps matching the unmapped key elsewhere; a job
    /// scoped to another keyboard ignores it.
    #[test]
    fn scoped_mappings_refine_layer_rules_per_keyboard() {
        let maps = vec![map("KeyH", Some("J"), None, "kb1", false)];
        let layers = vec![layer("nav", "CapsLock", &[("KeyH", "Arrow Left", "all")])];
        let yaml = generate(&maps, &layers, kb1_named);
        assert!(yaml.contains(
            "  - name: 'Keyloom layer: nav, hold Caps Lock (Keychron K2 Pro)'\n\
             \x20   device:\n\
             \x20     only: ['Keychron K2 Pro']\n\
             \x20   remap:\n\
             \x20     KEY_BRL_DOT1-KEY_J: KEY_LEFT\n"
        ));
        assert!(yaml.contains(
            "  - name: 'Keyloom layer: nav, hold Caps Lock'\n\
             \x20   remap:\n\
             \x20     KEY_BRL_DOT1-KEY_H: KEY_LEFT\n"
        ));

        let layers = vec![layer("nav", "CapsLock", &[("KeyH", "Arrow Left", "kb2")])];
        let yaml = generate(&maps, &layers, kb1_named);
        assert!(yaml.contains("      KEY_BRL_DOT1-KEY_H: KEY_LEFT\n"));
        assert!(!yaml.contains("KEY_BRL_DOT1-KEY_J"));
    }

    /// A layer key's own mapping scoped to one keyboard keeps its tap
    /// action there, ahead of the entry that holds the layer everywhere.
    #[test]
    fn a_scoped_mapping_of_the_layer_key_refines_its_entry() {
        let maps = vec![map("CapsLock", Some("Escape"), None, "kb1", false)];
        let layers = vec![layer("nav", "CapsLock", &[("KeyH", "Arrow Left", "all")])];
        let yaml = generate(&maps, &layers, kb1_named);
        let scoped = yaml
            .find("      KEY_CAPSLOCK:\n        held: KEY_BRL_DOT1\n        alone: KEY_ESC\n")
            .expect("tap/hold entry for the keyboard");
        let general = yaml
            .find("      KEY_CAPSLOCK: KEY_BRL_DOT1\n")
            .expect("plain entry for every keyboard");
        assert!(scoped < general);
    }

    /// Physical modifiers always pass through xremap, and a key that
    /// holds a layer is remapped before rules apply: neither can take a
    /// job. A disabled job emits nothing.
    #[test]
    fn modifiers_and_layer_keys_take_no_jobs_and_disabled_jobs_emit_nothing() {
        let layers = vec![
            layer(
                "nav",
                "CapsLock",
                &[
                    ("ShiftLeft", "Home", "all"),
                    ("CapsLock", "Escape", "all"),
                    ("Space", "Enter", "all"),
                    ("KeyY", "Disabled", "all"),
                    ("KeyH", "Hyper", "all"),
                ],
            ),
            layer("num", "Space", &[("KeyJ", "1", "all")]),
        ];
        let yaml = generate(&Vec::new(), &layers, no_devices);
        assert!(!yaml.contains("KEY_LEFTSHIFT"));
        assert!(!yaml.contains("KEY_BRL_DOT1-KEY_CAPSLOCK"));
        assert!(!yaml.contains("KEY_BRL_DOT1-KEY_SPACE"));
        assert!(!yaml.contains("KEY_BRL_DOT1-KEY_H"));
        assert!(yaml.contains("      KEY_BRL_DOT1-KEY_Y: []\n"));
        assert!(yaml.contains("      KEY_SPACE: KEY_BRL_DOT2\n"));
        assert!(yaml.contains("      KEY_BRL_DOT2-KEY_J: KEY_1\n"));
        assert!(yaml.contains("virtual_modifiers:\n  - KEY_BRL_DOT1\n  - KEY_BRL_DOT2\n"));
    }

    /// Each layer takes the next modifier in profile order; layers past
    /// the pool, and layers without a known key, generate nothing.
    #[test]
    fn layers_take_modifiers_in_order_within_the_pool() {
        let triggers = [
            "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11",
        ];
        let mut layers: Vec<Layer> = triggers
            .iter()
            .map(|trigger| layer(trigger, trigger, &[("KeyH", "Arrow Left", "all")]))
            .collect();
        layers.insert(0, layer("unset", "", &[("KeyH", "Arrow Left", "all")]));
        layers.insert(
            0,
            layer("unknown", "NoSuchKey", &[("KeyH", "Arrow Left", "all")]),
        );
        let yaml = generate(&Vec::new(), &layers, no_devices);
        assert!(yaml.contains("      KEY_F1: KEY_BRL_DOT1\n"));
        assert!(yaml.contains("      KEY_F10: KEY_BRL_DOT10\n"));
        assert!(!yaml.contains("KEY_F11"), "{yaml}");
        assert!(yaml.contains("      KEY_BRL_DOT10-KEY_H: KEY_LEFT\n"));
        assert_eq!(yaml.matches("  - KEY_BRL_DOT").count(), MAX_LAYERS);

        let none = vec![layer("unset", "", &[("KeyH", "Arrow Left", "all")])];
        assert_eq!(
            generate(&Vec::new(), &none, no_devices),
            without_layers(&Vec::new())
        );
    }

    /// Write the layer documents that `scripts/verify-layers-with-xremap.sh`
    /// runs through xremap's own event-handler tests into
    /// `$KEYLOOM_HARNESS_DIR`; the expectations live beside the script.
    #[test]
    #[ignore = "writes files for the xremap harness script"]
    fn dump_documents_for_the_xremap_harness() {
        let dir = PathBuf::from(
            std::env::var("KEYLOOM_HARNESS_DIR")
                .expect("KEYLOOM_HARNESS_DIR names the output directory"),
        );
        let navigation = model::starter_profiles()
            .into_iter()
            .find(|starter| starter.profile.id == "navigation")
            .expect("navigation starter");
        // Caps Lock holds a layer with no tap action; Space taps a
        // space and holds a second layer.
        let two_layers = vec![
            Layer {
                name: "Navigation".to_owned(),
                ..layer(
                    "nav",
                    "CapsLock",
                    &[("KeyH", "Arrow Left", "all"), ("KeyY", "Disabled", "all")],
                )
            },
            Layer {
                name: "Numbers".to_owned(),
                ..layer(
                    "num",
                    "Space",
                    &[("KeyJ", "1", "all"), ("KeyH", "2", "all")],
                )
            },
        ];
        let space_taps = vec![map("Space", Some("Space"), None, "all", false)];
        // A job on a key whose normal press is remapped (H types J).
        let h_types_j = vec![map("KeyH", Some("J"), None, "all", false)];
        let nav_only = vec![layer("nav", "CapsLock", &[("KeyH", "Arrow Left", "all")])];
        for (name, yaml) in [
            (
                "navigation.yml",
                generate(&navigation.maps, &navigation.layers, no_devices),
            ),
            (
                "two-layers.yml",
                generate(&space_taps, &two_layers, no_devices),
            ),
            (
                "remapped-key.yml",
                generate(&h_types_j, &nav_only, no_devices),
            ),
        ] {
            fs::write(dir.join(name), yaml).expect("harness directory is writable");
        }
    }

    #[test]
    fn config_path_uses_keyloom_filename_in_xremap_directory() {
        let path = config_path().expect("test environment has a config or home directory");
        assert!(path.ends_with("xremap/keyloom.yml"));
    }

    #[test]
    fn write_respects_foreign_files_and_backs_them_up() {
        let temp = TempDir::new("write");
        let dir = temp.path();
        let path = dir.join("keyloom.yml");
        let ours = without_layers(&Vec::new());

        // Fresh write, then an identical write is a no-op.
        assert_eq!(
            write_to(&path, &ours, false).unwrap(),
            WriteOutcome::Written(path.clone())
        );
        assert_eq!(
            write_to(&path, &ours, false).unwrap(),
            WriteOutcome::Unchanged(path.clone())
        );

        // A hand-written file is preserved unless overwriting is allowed.
        fs::write(&path, "modmap: [] # hand written\n").unwrap();
        let updated = format!("{ours}# updated\n");
        assert_eq!(
            write_to(&path, &updated, false).unwrap(),
            WriteOutcome::SkippedForeign(path.clone())
        );
        assert_eq!(
            write_to(&path, &updated, true).unwrap(),
            WriteOutcome::Written(path.clone())
        );
        assert_eq!(fs::read_to_string(&path).unwrap(), updated);
        assert_eq!(
            fs::read_to_string(dir.join("keyloom.yml.bak")).unwrap(),
            "modmap: [] # hand written\n"
        );

        // Our own older output is replaced without a backup.
        assert_eq!(
            write_to(&path, &ours, false).unwrap(),
            WriteOutcome::Written(path.clone())
        );
        assert!(!dir.join("keyloom.yml.bak.1").exists());
    }

    /// End-to-end oracle against a real xremap binary: the pinned CLI
    /// loads its configuration *before* selecting devices, so pointing
    /// it at a device name that cannot exist distinguishes "config
    /// parsed" (fails preparing input devices) from "config rejected"
    /// (fails loading the config).
    ///
    /// Ignored during normal local tests to avoid launching the installed
    /// xremap. CI installs the pinned release and explicitly runs this test
    /// with `--ignored`; a missing binary is a failure.
    #[test]
    #[ignore = "launches xremap; CI runs this explicitly with a pinned binary"]
    fn generated_documents_parse_with_real_xremap() {
        use std::process::Command;

        // Every known physical key as a remap source.
        let sources: Vec<&str> = model::registry().map(|cap| cap.code).collect();
        let all_sources: Maps = sources
            .iter()
            .map(|code| map(code, Some("Escape"), None, "all", false))
            .collect();
        // Every translatable catalog action as an output (plus
        // Disabled; Hyper has no key and is dropped by the generator).
        // The catalog holds more actions than there are keys, so cycle
        // sources; one source keeps only its last action, which is fine
        // because every action still appears in some document chunk
        // below.
        let actions: Vec<&&str> = model::ACTION_GROUPS
            .iter()
            .flat_map(|(_, actions)| actions.iter())
            .collect();
        let all_action_chunks: Vec<Maps> = actions
            .chunks(sources.len())
            .map(|chunk| {
                chunk
                    .iter()
                    .enumerate()
                    .map(|(i, action)| map(sources[i], Some(action), None, "all", false))
                    .collect()
            })
            .collect();

        // Every layer modifier in use at once, with every non-modifier
        // key as a job in one layer and every action as a job's output
        // across the others.
        let triggers = ["F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10"];
        let job_keys: Vec<&str> = sources
            .iter()
            .copied()
            .filter(|code| !triggers.contains(code) && !is_modifier_key(code))
            .collect();
        let mut all_layers = vec![layer(
            "all-keys",
            triggers[0],
            &job_keys
                .iter()
                .map(|code| (*code, "Escape", "all"))
                .collect::<Vec<_>>(),
        )];
        for (i, chunk) in actions.chunks(job_keys.len()).enumerate() {
            let jobs: Vec<(&str, &str, &str)> = chunk
                .iter()
                .enumerate()
                .map(|(k, action)| (job_keys[k], **action, "all"))
                .collect();
            all_layers.push(layer(&format!("actions-{i}"), triggers[i + 1], &jobs));
        }
        for trigger in &triggers[all_layers.len()..] {
            all_layers.push(layer(trigger, trigger, &[("KeyH", "Arrow Left", "all")]));
        }
        assert_eq!(all_layers.len(), MAX_LAYERS);

        let mut documents = vec![
            ("empty".to_owned(), without_layers(&Vec::new())),
            (
                "representative".to_owned(),
                generate(&representative_maps(), &representative_layers(), kb1_named),
            ),
            ("all-sources".to_owned(), without_layers(&all_sources)),
            (
                "all-layers".to_owned(),
                generate(&Vec::new(), &all_layers, no_devices),
            ),
        ];
        for (i, chunk) in all_action_chunks.iter().enumerate() {
            documents.push((format!("all-actions-{i}"), without_layers(chunk)));
        }

        let temp = TempDir::new("validate");
        let dir = temp.path();
        for (name, yaml) in &documents {
            let path = dir.join(format!("{name}.yml"));
            fs::write(&path, yaml).unwrap();
            let output = Command::new("xremap")
                .arg("--device")
                .arg("keyloom-validation-no-such-device")
                .arg(&path)
                .output()
                .expect("xremap validation requires the pinned binary on PATH");
            let stderr = String::from_utf8_lossy(&output.stderr);
            assert!(
                !stderr.contains("Failed to load config"),
                "{name}: xremap rejected the generated config:\n{stderr}\n---\n{yaml}"
            );
            assert!(
                stderr.contains("Failed to prepare input devices"),
                "{name}: xremap did not reach device selection:\n{stderr}"
            );
        }
    }
}
